### ISSUE TITLE
Nefukční odkaz na zdroje dat - Cesko_bez_uhli_od_2030_Ember.pdf

### ISSUE THREAD

**Issue by vitekmilan** [faktaoklimatu/web-cz#1037]
Na stránce popisující podrobně scénáře Ember - https://faktaoklimatu.cz/studie/2020-scenar-ember odkazuje buttonek původní zdroje dat / shrnutí CZ - na stránku, která nefunguje. 

Buď je potřeba najít nový zdroj - což jsem nenašel, nebo nechat jen anglický odkaz. 

https://ember-climate.org/wp-content/uploads/2020/11/Cesko_bez_uhli_od_2030_Ember.pdf

**Comment by vitekmilan** [comment]
Neumím sem vložit vysokou prioritu, respektive label "chyba na webu".  :-(

**Comment by katkolouchova** [comment]
Už to upravuji, našla jsem nový odkaz, kde to je :)
