### ISSUE TITLE
Zkontrolovat nové stránky témat

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-cz#1100]
Prosím o kontrolu textů v `collections/_topics/*.md`:
- spellcheckerem,
- typograficky,
- jazykově.

Jazykově, editorsky a snad i typograficky to kontrolovala Káťa, ale textů je to hodně, tak se druhý pár očí hodí.

**Comment by crysman** [comment]
du na to

**Comment by crysman** [comment]
mno, trochu zásek, nemůžu si zbuildit web... https://github.com/faktaoklimatu/web-cz/issues/1102

**Comment by crysman** [comment]
done.
https://github.com/faktaoklimatu/web-cz/pull/1103
