### ISSUE TITLE
nejde zbuildit repo

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web-cz#1102]
Stáhl jsem si poslední verzi z repo.
Prereqs jsou splněny.
Přesto mi nejde zbuildit :(

![image](https://user-images.githubusercontent.com/5269350/184547576-9d8cddfe-30e9-4d37-96dd-997502818587.png)

V čem je prosím chyba?
pravděpodobně se jedná o problém popisovaný zde: https://stackoverflow.com/a/62085185/2878211 neb já samozřejmě používám klíč s heslem... jaké máme ofiko solution plz? @mukrop ? @mgrabovsky ?

**Comment by jankrcal** [comment]
@mukrop Je to stejný bug, na který jsi narazil Ty?

Každopádně je to zvláštní, zdá se, že to selže na 
 `git submodule update --init --recursive` na web-core. K tomu máš ale normálně write access (a navíc ho zde ani nepotřebuješ).

Můžeš @crysman zkusit spustit make local z web-core?

**Comment by mukrop** [comment]
Myslim, ze to nie je rovnaka chyba, u mna bol problem s inkscapom, u crysmana to vyzera na permission error.
(a ospravedlnujem sa, ale v najblizsich dnoch nebudem mat kapacitu to debugovat)

**Comment by crysman** [comment]
Mno, hoši... oprávnění jsou default, já to dělal from-scratch, čili čerstvý git clone.

Každopádně, obě ty "symlinkové" složky 
![image](https://user-images.githubusercontent.com/5269350/185230662-8901724a-c8f4-431b-883e-8b929f65c481.png)
 jsou prázdné po clone, což je asi OK, nicméně, make local si je nenapulluje.
![image](https://user-images.githubusercontent.com/5269350/185230545-c979eaf9-4b03-4739-bbf3-310f128f72df.png)

make local z web-core nedává smysl, když to je prázdné - nepřekvapivě si make stěžuje:
![image](https://user-images.githubusercontent.com/5269350/185231010-2fe4845a-44c6-43b0-b840-ee2202590305.png)
(a není divu, když tam není Makefile)

Vám to jako nedělá? Zkuste si to naklonovat do nového adresáře a zbuildit - což? @jankrcal @mukrop @mgrabovsky ?

**Comment by mgrabovsky** [comment]
@crysman Pokud máš zaheslovaný SSH klíč, zkus použít [ssh-agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent).

**Comment by mukrop** [comment]
Ja som to klonoval z cista nedavno a fungovalo mi to v pohode.

A `make local` si tie submoduly natiahne sam, to je presne ten prikaz,
ktory ti spadne.

Matej ma dobry tip, pada ti `git submodule` na opravneniach a podla obrazka
tahas ssh, takze mas problem tam. Este si prosim over, ze mas pristup do
tych repozitarov – moze to byt aj problem na nasej strane, ak sa napriklad
nedostanes do 2050podcast.

**Comment by crysman** [comment]
do podcastu se dostanu a toho druhého submodulu taky
![image](https://user-images.githubusercontent.com/5269350/185656094-de693ea4-ae94-4c5b-8e35-eea8e0b6d944.png)

jdu zkusit poštělovat toho ssh-agenta... díky

**Comment by crysman** [comment]
tak pořád nic, nechápu, zde co jsem udělal:

- [x] ověřit že v GH mám ten klíč, co si myslím, že mám (stejný fingerprint)
![image](https://user-images.githubusercontent.com/5269350/185657808-0659b744-1b04-4769-a3f1-3f11973e2666.png)
![image](https://user-images.githubusercontent.com/5269350/185657868-a040dcf5-bf7b-4e53-93f3-cc79d3feff7d.png)
- [x] přidat klíč do ssh agenta dle [zmíněného návodu](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent):
![image](https://user-images.githubusercontent.com/5269350/185658539-1fae5d24-1ef3-485d-861e-8d21d549f985.png)
- [ ] pořád stejný error :(
![image](https://user-images.githubusercontent.com/5269350/185658808-0fc3a670-7cbf-4671-9b48-779aa5a327bd.png)

chjo...

**Comment by crysman** [comment]
dočasně vyřešeno přes `git submodule update --init --recursive` ([zdroj](https://github.com/riscv-collab/riscv-gnu-toolchain/issues/923#issuecomment-871607769)) - ale ideální to není rozhodně...

![image](https://user-images.githubusercontent.com/5269350/185659327-8c703299-ffb9-453e-bca3-179cfd7306f2.png)

**Comment by crysman** [comment]
ne, nevyřešeno, sice se tam pullnuly files do obou modulů, ale **make local pořád padá na stejné chybě** :(

![image](https://user-images.githubusercontent.com/5269350/185659905-c9bdef6e-fdd0-402a-90dd-beadbb4e0b0a.png)

**Comment by jankrcal** [comment]
Tomu už vůbec nerozumím.

Píšeš ze se podařilo pullnout submodules pomocí `git submodule update --init --recursive `.
Ale vždyť to je úplně ten stejný příkaz, který ti v rámci `Makefile` padá!

Nepoužíváš nějaký nestandardní setup pro Makefile?

Když se dívám na tu chybovou hlášku, tak mi to spíš připadá, že `make` vůbec nemůže spustit `git`, jako by měl jinak nakonfigurovaný path a příkaz `git` tam nebyl executable, nebo tak něco.

**Comment by jankrcal** [comment]
Ostatně i Error 127 vede ke stejnému závěru: https://linuxconfig.org/how-to-fix-bash-127-error-return-code

**Comment by crysman** [comment]
já to taky nechápu, dle GH [návodu](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection) i test SSH probíhá korektně:
![image](https://user-images.githubusercontent.com/5269350/185765474-fb99ac8e-3f31-422d-9838-9e47d1b82659.png)
To je fakt pakárna, asi nezbude než si založit klíč bez passphrase pro FoK :(

**Comment by jankrcal** [comment]
Jak píšu výše, podle mě to ale vůbec není problém s autentizací, spíš bych debuggoval `make`

**Comment by crysman** [comment]
tak, díky [StackOverflow máme řešení](https://stackoverflow.com/questions/62561355/permission-error-running-any-git-command-in-makefiles/62562135#comment124673218_62562135), zde výtah:

1. ano, v `make` 4.3 je bug // co máte vy za make? @jankrcal @mgrabovsky @mukrop ?
2. je třeba přidat středníky za git-related příkazy v Makefile, přikládám patch [Makefile.patch.txt](https://github.com/faktaoklimatu/web-cz/files/9389944/Makefile.patch.txt)

**Comment by jankrcal** [comment]
Udělal jsem PR pro `web-cz` (požádal Tě o review) a do `web-en` jsem to vmáčknul do otevřeného https://github.com/faktaoklimatu/web-en/pull/8.

Pokud to bude Tobě fungovat ve `web-cz`, můžeš prosím udělat analogický PR pro `web-sk`?

**Comment by jankrcal** [comment]
(já mám `make` 3.81)

**Comment by crysman** [comment]
@mgrabovsky to jsem kontroloval, v PATH `git` nemám:
![image](https://user-images.githubusercontent.com/5269350/185881978-2d7313ce-cd22-4517-b51e-d19f2951dda1.png)

**Comment by mgrabovsky** [comment]
Hm, tak možná je to ve Fedoře nějak patchnuté :man_shrugging:

**Comment by crysman** [comment]
je tu popsaný workaround i patch,
bug fixnou upstream časem tipuju, zde tedy zavírám, díky všem za spolupráci
