### ISSUE TITLE
Drobné zpřesnění v explaineru "Jak se na trhu stanovuje cena elektřiny?"

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-cz#1112]
Vyžaduje úpravy mini-grafik, tak zakládám issue, až bude čas:
 - variabilní náklady na výrobu z jádra změnit z 25 EUR na 10 EUR
 - dobu náběhu u jádra změnit na "Jednotky dnů; u novějších reaktorů lze výkon regulovat v nižších jednotkách hodin"
 - trochu bych potlačil záporné ceny u jádra, protože je to zbytečně matoucí, místo -10 EUR bych cenu u jádra dal -epsilon (podobně jako u OZE je + epsilon) ale komentář "Jaderné elektrárny je složité vypnout" bych nechal tak, jak je.
 - v animaci zisku v merit orderu by měl být provozní zisk u jádra až od hladiny 10 EUR (protože i když je bid nižší než 10 EUR, tak stejně ty náklady mají) - nevím ale, jak bude srozumitelné
 - V odstavci "Druhým nejlevnějším zdrojem jsou..."
   - můžem trochu oslabit drahost jádra - spíš bych to přeformuloval na vysoké investiční riziko.
   - Taky můžeme oslabit nízkou schopnost regulace: 
     - jádro sníží výkon i krátkodobě, pokud to umí. Nechá jen minimální provozní výkon, tím omezí ztrátu (ušetří za palivo).
     - Přidal bych větu, pokud ovšem by takový nadbytek měl trvat více dnů v kuse, může se jádru vyplatit úplně odstavit a pak nastartovat.

**Comment by jankrcal** [comment]
Druhá možnost je vykašlat se na určitou anomalii trhu, když jádro potřebuje obchodovat na spotu a dát jádru bid 10 EUR. Zjednoduší to argumentaci a vizualizace.

Bude to velmi dobře odpovídat futures trhu a současně i situaci na spotu s flexibilním jádrem. To, že někdy jádro biduje za zápornou cenu, aby se dostalo před OZE a nemuselo vypínat se dá zmínit do textu.

**Comment by jankrcal** [comment]
@jakub-zamouril Máš na to výše nějaké názory?

(vychází z tw feedbacku, rozhodně není urgentní ani prioritní)

**Comment by jakub-zamouril** [comment]
> Vyžaduje úpravy mini-grafik, tak zakládám issue, až bude čas:
> 
>     * variabilní náklady na výrobu z jádra změnit z 25 EUR na 10 EUR

ok

> 
>     * dobu náběhu u jádra změnit na "Jednotky dnů; u novějších reaktorů lze výkon regulovat v nižších jednotkách hodin"
> 

ok, pokud se vejde

>     * trochu bych potlačil záporné ceny u jádra, protože je to zbytečně matoucí, místo -10 EUR bych cenu u jádra dal -epsilon (podobně jako u OZE je + epsilon) ale komentář "Jaderné elektrárny je složité vypnout" bych nechal tak, jak je.
> 

jo, to dává smysl

>     * v animaci zisku v merit orderu by měl být provozní zisk u jádra až od hladiny 10 EUR (protože i když je bid nižší než 10 EUR, tak stejně ty náklady mají) - nevím ale, jak bude srozumitelné
> 

asi za účelem srozumitelnosti bych to nechal jak to je, i za cenu mírné nepřesnosti

>     * V odstavci "Druhým nejlevnějším zdrojem jsou..."
>       
>       * můžem trochu oslabit drahost jádra - spíš bych to přeformuloval na vysoké investiční riziko.
>       * Taky můžeme oslabit nízkou schopnost regulace:
>         
>         * jádro sníží výkon i krátkodobě, pokud to umí. Nechá jen minimální provozní výkon, tím omezí ztrátu (ušetří za palivo).
>         * Přidal bych větu, pokud ovšem by takový nadbytek měl trvat více dnů v kuse, může se jádru vyplatit úplně odstavit a pak nastartovat.

Stěžovali si milovníci jádra? :) podle mě napsat že jádro je drahé je oprávněné, i na základě lifecycle analysis z literatury. Nebo je nějaký zdroj který říká něco jiného? Co se týče schopnosti regulace tak můžeme přidat zmínku, tu jsme pokud si dobře pamatuju taky vynechali v zájmu stručnosti a srozumitelnosti.

**Comment by jankrcal** [comment]
Po dalším feedbacku od Jiřího Beranovského se přikláním k řešení, které popisuju v https://github.com/faktaoklimatu/web-cz/issues/1112#issuecomment-1232838117.
