### ISSUE TITLE
rozbitý odkaz na stránce "Světové emise CO₂ z fosilních paliv a výroby cementu"

### ISSUE THREAD

**Issue by tjarnikova** [faktaoklimatu/web-cz#1130]
Odkaz v odstavci o těžbě a přepravě je rozbitý (soubor už neexistuje na webu BP ): 

Těžba a přeprava: Celkově se za rok 2019 vytěžilo [4000 miliard m3](https://www.bp.com/content/dam/bp/business-sites/en/global/corporate/pdfs/energy-economics/statistical-review/bp-stats-review-2019-natural-gas.pdf), tedy asi 3,2 miliard tun zemního plynu. Mezi největší producenty patří USA (21 % světové produkce), Rusko (17 %) a státy Perského zálivu (dohromady 18 %). [Přeprava zemního plynu](https://en.wikipedia.org/wiki/Natural_gas#/media/File:Global_Gas_trade_both_LNG_and_Pipeline.png) probíhá jak skrz plynovody, tak pomocí lodí, které přepravují zkapalněný plyn.

Rozbitý link:
https://www.bp.com/content/dam/bp/business-sites/en/global/corporate/pdfs/energy-economics/statistical-review/bp-stats-review-2019-natural-gas.pdf

**Comment by katkolouchova** [comment]
Díky za upozornění, upravím! :)
