### ISSUE TITLE
Odkazy na autory příručky Extrémy

### ISSUE THREAD

**Issue by vitekmilan** [faktaoklimatu/web-cz#1145]
Na stránce překladu "[Extrémů - kompasu](https://faktaoklimatu.cz/explainery/vliv-klimatu-na-extremy-prirucka?q=extre)", potřebujeme upravit odkaz na autory text. V současnosti vedou odkazy autorů na naše stránky, potřebujeme je upravit následovně: 

- Ben Clarke - https://twitter.com/BennethClarke
- Otto - https://twitter.com/FrediOtto 

Bavil jsem se o tom již s @jankrcal, který chce celou sekci upravit komplexněji. A již víme, že se to nebude dělat ve sprintu leden - březen 2023.

**Comment by katkolouchova** [comment]
Tzn. i potenciální stránka s pdf příručky (jako máme s Atlasem) spadne až k těmto úpravám? @vitekmilan

**Comment by jankrcal** [comment]
Toto vyřeší https://github.com/faktaoklimatu/web-cz/pull/1169 (na stránce PDF příručky) a https://github.com/faktaoklimatu/web-cz/pull/1182 (na stránce explaineru).
