### ISSUE TITLE
Nefunkční odkaz na zdrojová data EPICA

### ISSUE THREAD

**Issue by vitekmilan** [faktaoklimatu/web-cz#1181]
Na stránce https://faktaoklimatu.cz/datasety/koncentrace-co2 směřuje odkaz na data EPICA na 404. (Kde jsou ta data k dispozici jinde a stabilně netuším.)

**Comment by mgrabovsky** [comment]
On ten odkaz funguje, jenom asi ne v prohlížeči, který neumí FTP (Firefox, nevím jak Chrome). Ale i tak by za mě bylo obecně lepší odkazovat na stránky s informacemi o datasetu spíš než rovnou na soubor s tabulkou. V tomhle případě i níže v textu odkazujeme na <https://www.ncei.noaa.gov/access/paleo-search/study/17975>.

**Comment by vitekmilan** [comment]
Prohlížel jsem v Safari. 

Klikal jsem ale na stránce datasetu na buttonek zdroje dat, kde jsem kliknul na EPICA. A tam mne to hodil a 404. (FTP neumím posoudit)

**Comment by vitekmilan** [comment]
+ chrome mi to umí otevřít, respektive mne přesměrovat na FTP klienta.
