### ISSUE TITLE
Studie: IPCC SR Ocean and Cryosphere

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#201]
https://www.carbonbrief.org/in-depth-qa-the-ipccs-special-report-on-the-ocean-and-cryosphere?utm_source=TwitterVid&utm_medium=social&utm_campaign=IPCCoceans0919

https://ekolist.cz/cz/publicistika/nazory-a-komentare/radimn-tolasz-dalsi-zprava-ipcc-oceany-a-kryosfera-v-menicim-se-klimatu

**Comment by ondraspribyla** [comment]
https://www.greenpeace.org/czech/tiskova-zprava/4389/nova-zprava-klimatologu-oceany-v-krizi-roztavani-ledovcu-a-zvysovani-morske-hladiny/

**Comment by ondraspribyla** [comment]
![Projected-changes-in-glacier-mass-between-2015-and-2100-under-emission-scenarios-RCP2-and-RCP8](https://user-images.githubusercontent.com/17317136/66167228-d7d38a00-e639-11e9-9684-0cf4880bb02b.jpg)
IPCC SROCC CHapter 2

**Comment by mukrop** [comment]
Přesunuto na wiki.

**Comment by ondraspribyla** [comment]
Myslím, že ze studií přejdeme postupně na explainery - které narozdíl od shrnujících studií jsou tématicky jasněji vymezené. Proto zavírám...
