### ISSUE TITLE
Manuál: grafika, texty, styl, typografie

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#234]
Výsledkem by měl být explicitní KNOW-HOW, tedy manuál. 
- [x] manuál zde https://docs.google.com/document/d/1wVQv4w93Qg_ma6HNFn2Zs3iYQqlo6MKnQiwMHsF2pvA
- [x] udělat z toho .md či nějak jinak to zakomponovat do workflow v rámci GitHubu (navrhl i Jeňa)
- [x] Jednotky - jsou uvedeny, případně vysvětleny a čitelné? 

Zde je draft manuálu workflow a typografie k infografikám: https://docs.google.com/document/d/1JF0J4Tg_Xr6iTui2-FX2_J_Aev3NWrZnS3zly1Ct500/edit#

**Comment by ondraspribyla** [comment]
kopie z #98
- Veci, ktore casto zabudame (medzery pred stupnami Celsia, rozdelovniky vs. pomlcky, medzerty pred jednotkami, desatinna ciarka vs. bodka, ...).
- Aku typografiu pouzivame (tj. poseme – alebo unicode znak pre pomlcku?).
- Par zasad k obsahu textov (su faktograficke, nie aktivisticke, vyhybame sa nepodlozenym tvrdeniam a pod.).
- Podla takto spisanych zasad potom zjednotit existujuce texty (napr. tie pomlcky).

**Comment by ondraspribyla** [comment]
souvisi s #60

**Comment by mukrop** [comment]
Poznamka: Pouzivame ASCII uvodzovky (je nasadena automaticka konverzia na smart quotes).

**Comment by crysman** [comment]
založil jsem
https://docs.google.com/document/d/1wVQv4w93Qg_ma6HNFn2Zs3iYQqlo6MKnQiwMHsF2pvA/edit#heading=h.7zhnsm8jab4a
a du tam dát nástřel

**Comment by crysman** [comment]
co je tady prosím next step?

upravil jsem první post se svým návrhem

**Comment by mukrop** [comment]
@crysman dik sa spisanie, zacina to mat dobry tvar! Este by to mohla prejst @LenkaSedlackova 
Aktualne by som to nechal ako Google doc, vznikaju tam aj ostatne navody. Casom to mozno presunieme na wiki alebo do gitu – rozhodneme sa podla toho, kolko toho bude a co v tych navodoch bude.

**Comment by LenkaSedlackova** [comment]
prišla som. videla som. okomentovala som :)

**Comment by LenkaSedlackova** [comment]
+ #576

**Comment by ondraspribyla** [comment]
Je zde nějaký next step? Jaký stav můžeme považovat za dokončení issue? 
Nebo jde o dlouhodobou věc, kdy chceme někam hromadit Know-how?

**Comment by mukrop** [comment]
Pravdepodobne preklopit na nejake "oficialne" dobre dostupne miesto. Za mna asi na GitHub, ale musim sa zamysliet. Visi to aktualne na mne, ale nie je to az tak vysoko prioritne, aby som sa k tomu zatial dostal.

**Comment by jankrcal** [comment]
Jinak samotné překlopení mi taky přijde supr úkol pro nováčky se zájmem o psaní textů - seznámí se při tom člověk technicky s tím, jak psát na náš web.

**Comment by mukrop** [comment]
Ano, dobry point.
Vybral by som miesto, kam to dat (osobna diskusia na vikende), mozno skusil
tam premigrovat onboarding dokument (suvisi s diskusiou, ci zacat tlacit
Notion alebo nie).

>

**Comment by mukrop** [comment]
Manualny na Notione (Provozni > Manualy), odkazovane aj z noveho Readme repozitara.
