### ISSUE TITLE
Studie: IPCC SRCCL

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#253]
Zdroje: 
https://cs.wikipedia.org/wiki/Zvl%C3%A1%C5%A1tn%C3%AD_zpr%C3%A1va_IPCC_o_zm%C4%9Bn%C4%9B_klimatu,_krajin%C4%9B_a_p%C5%AFd%C4%9B

https://www.carbonbrief.org/in-depth-qa-the-ipccs-special-report-on-the-ocean-and-cryosphere

https://www.carbonbrief.org/in-depth-qa-the-ipccs-special-report-on-climate-change-and-land.

**Comment by protivinsky** [comment]
Predpokladam ze toto je autor obou IPCC wiki clanku: https://www.czp.cuni.cz/czp/index.php/cz/pracovnici-kontakty/81-ing-jiri-dlouhy
Jiri Dlouhy, jiri.dlouhy@czp.cuni.cz

**Comment by ondraspribyla** [comment]
https://www.carbonbrief.org/in-depth-qa-the-ipccs-special-report-on-the-ocean-and-cryosphere

**Comment by ondraspribyla** [comment]
Myslím, že přecházíme z formátu Studie na formát explainery které jsou tematicky jasněji vymezené. Tímto issue zavírám...
