### ISSUE TITLE
Studie: IPCC SR15

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#254]
https://cs.wikipedia.org/wiki/Zvl%C3%A1%C5%A1tn%C3%AD_zpr%C3%A1va_IPCC_ke_glob%C3%A1ln%C3%ADmu_oteplen%C3%AD_o_1,5_%C2%B0C

- [x]  najit a zkontaktovat autora textu na wiki @crysman 

- [ ] upravit, vylepsit, zkontrolovat  a mozna ve spolupraci s autoretm textu na wiki publikovat u nas

**Comment by protivinsky** [comment]
Predpokladam ze toto je autor obou IPCC wiki clanku: https://www.czp.cuni.cz/czp/index.php/cz/pracovnici-kontakty/81-ing-jiri-dlouhy
Jiri Dlouhy, jiri.dlouhy@czp.cuni.cz

**Comment by crysman** [comment]
vypadá, že to je on, napsal jsem mu maila:

> Dobrý den,
> 
> chtěl bych se zeptat, zda to jste Vy, Jiří Dlouhý, který primárně edituje tyto Wikistránky: https://cs.wikipedia.org/wiki/Zvl%C3%A1%C5%A1tn%C3%AD_zpr%C3%A1va_IPCC_ke_glob%C3%A1ln%C3%ADmu_oteplen%C3%AD_o_1,5_%C2%B0C
> 
> - pokud ano, díky moc za Vaši investici do vzdělávání a informovanosti veřejnosti! Já jsem členem jádra týmu [faktaoklimatu.cz](https://faktaoklimatu.cz), kde související věci řešíme. V současné době uvažujeme i o začlenění IPCC-SR15 do našich stránek, a pokud se tak stane, velmi pravděpodobně budeme čerpat z vašeho Wiki článku, a popř. ho i nějak upravovat. Jste s tím OK?
> 
> Mimochodem, pokud byste měl zájem o spolupráci s naším týmem, rádi uvítáme někoho externího pro příležitostné revize - jedním s našich pilířů je kredibilita, a jednou ze strategií, jak kredibilitu zvyšovat je nechat se "dozorovat" odborníky v oboru...
> 
> Díky moc
> Martin crysman Zahradník

odpověď sem vložím

**Comment by crysman** [comment]
odpověď přišla. Zde výtah:

1. ano, je to on
1. upravuje vícero stránek s touto tématikou
1. už prý spolupracuje s Ondrášem a navíc mu prý psal ještě někdo - zdá se, že jsme v tom lehce chaotičtí - navrhuju, aby tasky dělal jejich assignee, a pokud někdo jiný, aby dal vědět - ať neděláme zbytečnou práci a nevypadáme jak hejno chaosáků
1. ano, je pro další spolupráci
1. prý dával na CCommons nějaké naše grafy, a skutečně, zde: https://cs.wikipedia.org/wiki/Glob%C3%A1ln%C3%AD_oteplov%C3%A1n%C3%AD_v_%C4%8Cesku - to A) považuju za důvod k radosti a oslavě B) založím k tomu dvě návazné issues   ... (je na tu stránku hrdý, dostala ocenění "dobrý článek")
1. bude rád pokud mu někdo pomůže s editací Wiki ohledně GCC (nemám rád termín globální oteplování, a proto používám GCC (global climate changes))
1. odepsal jsem mu

**Comment by mukrop** [comment]
Cau. O tej stranke "globalni oteplovani v Cesku" vieme, islo to aj klimaton mailing listom ako jedno z prvych pouziti, Ondras sa s nim o tom bavil este pred tym. Ohladom tejto stranky s grafmi som mu pisal ja, pretoze tam mal nahratu staru verziu a my sme mali vyrazny update (suvisiace bolo #64).

**Comment by VladaSedlacek** [comment]
Na GDrivu ve složce IPCC je soubor "IPCC SR15 #254 - text na web - ucelený", do kterého jsem sepsal návrh textu na web, který vychází z wiki stránky zmíněný výše a je doplněný o některé body z https://www.carbonbrief.org/in-depth-qa-ipccs-special-report-on-climate-change-at-one-point-five-c. Na začátku souboru je krátké TO DO.

**Comment by protivinsky** [comment]
Doplnuji primy odkaz, at to vsichni nehledame:
https://docs.google.com/document/d/1bf3Fk9dm4Nz-3EcD7aYu565GMKLakT2Fy7kDCzOZYOI

**Comment by ondraspribyla** [comment]
Našel jsem pouze soubor "...text na web - nápady" - ten "uceleny" na gdrivu
nevidím. V čem by mohl být problém?

O.

Dne ne 16. 2. 2020 17:02 uživatel VladaSedlacek <notifications@github.com>
napsal:

**Comment by VladaSedlacek** [comment]
Už by to mělo být v pořádku.

**Comment by ondraspribyla** [comment]
Msylím, že ze studií přecházíme na explainery, které jsou tématicky jasněji vymezené... tímto issue zavírám.
