### ISSUE TITLE
zdrojáky infografik v uložišti

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web-cz#266]
Přijde mi, že bychom měli mít vždy **aktuální zdrojáky všech infografik** v uložišti. Z hlediska oprávnění bych dal přístup pouze pro core. "Uložiště" používám záměrně, aby to nebylo zbytečně konkrétní.

Problém:
Nevidím tam ani jednu v žádné verzi, natož aktuální.

Proč to tak chci:
Protože chceme držet projekt people-independent, resp. ano, jsme důležití, ale měli bychom být zastupitelní.

**Comment by mukrop** [comment]
Nerozumiem otazke. PDF, co stiahnes z webu je plnohodnotny editovatelny subor.
Podklady v Illustratore su zdielane na spolocnom disku medzi vsetkymi grafikmi, zalohovy pristup mam ja. Nevidim dovod, preco by tam mali mat pristup dalsi ludia (skoro ani preco by som tam mal mat pristup ja, ale svojim sposobom fungujem ako backup).
Mat to so zbytkom veci mi pride nestrategiocke, pretoze to bude znamenat mat graficke podklady na viacerych miestach a velmi vysoke rizitko nekonzistencie.

Issue by som zavrel, cakam na tovju reakciu.

**Comment by crysman** [comment]
Jsme projekt. Data patří projektu, chtěl bych, aby to tak bylo. Pokud mají grafici uložiště jinde, je to nekoherentní a nekonzistentní. Řešením je podle mě dát data projektu, a ne je mít jinde - a tím se řeší i případná duplicita a nekonzistence. Ondráši? @ondraspribyla

**Comment by mukrop** [comment]
Presunute v gitovom repe (private pre tim projektu).
