### ISSUE TITLE
Grafika k překladu: Carbon Budget (Carbon Brief)

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#337]
Jednoduchá grafika. Celkem přehledný výpočet (odkazuje na něj článek)
https://www.carbonbrief.org/analysis-four-years-left-one-point-five-carbon-budget

@jankrcal můžeš na to prosím kouknout a srovnat to se starým issue, ve kterém jsme chtěli Carbon Budget zobrazit?

@kikinna Co si o tom myslíš z pohledu grafiky?

**Comment by jankrcal** [comment]
Ano, kouknu na to.

**Comment by jankrcal** [comment]
Přijde mi, že přímo překládat tuto grafiku je zavádějící, protože carbonbrief sám v tom článku uvádí, že mají novější komplexnější analýzu [1] a že IPCC v 1.5C SR sám upravil [2] (dost zvětšil) budget pro 66% šanci zůstat pod 1.5C.

Tato novější analýza [1] je odkazovaná ze staršího issue #110 .

Domluvili jsme se s Ondrášem, že:
 - grafiku / grafiky ke carbon budget budeme dělat, i když to může být hodně práce,
 -  já budu garantovat práci (aby se to stalo), Ondráš (příp. někdo další) konzultuje odborně.

Další kroky:
 - probrat s Kikou grafický koncept prezentace carbon budget a spol. (např. integrál emisí),
 - napsat carbonbrief, zda můžeme překládat jejich věci, inspirovat se infografikami (odkazovat),
 - připravit data.

[1] https://www.carbonbrief.org/analysis-how-much-carbon-budget-is-left-to-limit-global-warming-to-1-5c
[2] https://www.carbonbrief.org/analysis-why-the-ipcc-1-5c-report-expanded-the-carbon-budget

**Comment by jankrcal** [comment]
Dodatek z debaty s Ondrášem: časem by možná stálo za to udělat studii z překladu detailního textu z carbon brief.

**Comment by jankrcal** [comment]
Pokud bychom chtěli zobrazovat CO2eq budget, nutně by to znamenalo:
 - nastudovat literaturu k emisním scénářům
 - víc nastudovat / pochopit, proč toto nikdo neprezentuje.

Jako první krok je jistě udělat grafiky jen kolem carbon budget. Časem třeba rozšířit / upravit na CO2eq.

**Comment by jankrcal** [comment]
Jeste jeden zdroj z puvodni #110:
https://informationisbeautiful.net/visualizations/how-many-gigatons-of-co2/

**Comment by jankrcal** [comment]
Zápis z diskuse s Kikou:

Otázka, na kterou chceme odpovědět:
Proč ta urgence kolem toho tématu? Už se to řeší 30 let, tak proč teď taková hysterie? Nemůžeme ještě 10 let počkat a vidět, co se děje? Nemůžeme snižování emisí dělat víc v klidu (tedy levněji)?

Nápady na vizualizace k datasetu historické emise:

1) Zobrazit růst světových ročních emisí CO2 od roku 1960 (nebo ještě dřív) a znázornit, jaký budget jsme měli v roce 1991, 2009 a  jaký budget máme teď v roce 2019. Tedy, že je potřeba čím dal urgentnější akce.
  - Zobrazit například jako tři polotransparentní plochy různých barev, takže je vidět, jak se překrývají a že jsou každá podobně velká.
  - Místo zobrazování budgetu jako obdélníky na úrovni momentálních emisí, které na konci ostře klesnou k nule dáváme na zvážení to zobrazit jako lineárně klesající trojúhelníky. To sice každý ten budget zvětší přesně na dvojnásobek roků, za to to ale je něco mnohem blíže realistickému scénáři vývoje emisí.

K tomuto zobrazení se váže otázka, zda můžeme pro zjednodušení předpokládat, že každý ten budget je stejně velký a nebo zda se musíme hrabat v útrobách CO2 modelů, abychom zjistili, kolik volného budgetu bylo např. v roce 1991.

Co tato infografika neřeší je proč bychom se měli snažit udržet nárůst teplotní anomálie pod 1.5 stupně. Na to pořád nemáme grafiku, jistě stojí za separátní issue.

2) Zobrazit jen křivku růstu světových emisí CO2eq (příp. pro jednoduchost opět jen CO2). Zobrazit na tom, kolik procent světových emisí GHG bylo vypuštěno během života lidí, kteří jsou teď v různém věku. Např. na imaginární rodince 15 leté dítě, 45 letý rodič, 70 letý prarodič.
 - Ty čísla jsou scary, 15 leté dítě zažilo např. cca 33% emisí. 70 letý prarodič bude určitě přes 75%.

**Comment by kikinna** [comment]
Ahojte @jankrcal @ondraspribyla 
Jaký je aktuální stav s carbon budget a kam se budeme posouvat? 
Já sem nahazuji jen zběžně rozpracovanou verzi carbon budget ještě na styl "information is beautiful", kde bychom mohli pěkně a jednoduše vysvětlit, co to carbon budget je. Co myslíte, stojí za to to mít? (pak by to chtělo zpracovat podklady, přesné hodnoty, atd.)
A jaké další aspekty byste potom chtěli zobrazit? (narážím třeba na ten carbon countdown, atd.)

![Uhlikovy rozpocet-01](https://user-images.githubusercontent.com/11555522/75120758-533be380-568e-11ea-87ff-c51baa656bac.png)

**Comment by ondraspribyla** [comment]
Diky za nahozeni ;-)

**Comment by jankrcal** [comment]
Taky děkuju za rozhýbání diskuse.

Já jsem na datech začal pracovat, ale zasekl jsem se na dohledání spolehlivých zdrojů, kolik je fossilnich paliv v zemi. V tom datasheetu na informationisbeatuful jsem dobrej zdroj nenasel, tak jsem se zacal rypat v rocence BP, ale je to jeste prace a nevim, k jak podobnym cislum dojdu :)
https://docs.google.com/spreadsheets/d/1GeFBZXfLfvXyy56g1U_hLxjDTfI-rF2bej0ikrQPGr4/edit#gid=979818322

A taky jsem narazil na vice filosofickou otazku, co presne na te grafice zobrazovat.
 - Informationisbeatuful ma ciste minule & budouci emise z fosilnich paliv. To je jednoduchy a vcelku logicky, ale zato ne uplny.
 - Drivejsi rozpracovana data (https://docs.google.com/spreadsheets/d/1_E44UHwhhtPNntU5NUwwMgw-4PIZibYV73-R7s6_NoE/edit#gid=0) poskytuji skrz Global Carbon Budget i hodnoty minulych emisi skrz Land Use & Land Use Change (primarne odlesnovani). Je to podle jejich odhadů asi o polovinu víc než když bereme jenom fosilní paliva, viz níže:

![image](https://user-images.githubusercontent.com/145227/75538123-69dc9480-5a18-11ea-8df4-e5a9c7e17043.png)

**Comment by jankrcal** [comment]
Ještě ke draftu grafiky:

Přijde mi, že není zřejmý, jestli ta žlutá je současně i součástí toho světle červenýho; (to horní svorka zbývající zásoby to tak naznačuje, ale není mi zřejmé, v jaké formě fosilního paliva to žluté je)

Nevím, jestli nechceme spíš vizuálně naznačovat rozcestí: 
  - mít ty dvě modré vlevo, tak jako to je,
  - pak mít tlustou čáru teď jsme tady v čase
  - doprava (do budoucna) mít jakoby dva scénáře o stejné výšce sloupce, jakou má modrá, ať je to srovnatelné. Ty dva scénaře třeba zarovnat nad sebou, ať se dá snadno porovnávat jejich šířka:
     1. zbývající budget (příp. s naznačením nejistot)
     2. zbývající známá fosilní paliva v zemi
    (a nebo i 3. ve stejném stylu: kolik vypustíme za 1 rok) 

Je to srozumitelné, co tím myslím, nebo to mám nakreslit?

**Comment by kikinna** [comment]
@jankrcal Jéni, souhlasíš, že můžu zavřít? Nebo se v rámci této issue chtělo zobrazit ještě něco víc?

**Comment by ondraspribyla** [comment]
Jasně... jsem si myslel, že si užiješ ty dopaminy, nebo jaké hormony to jsou z dokončené práce a uzavření issue... a takhle si je dám s radostí já (zrovna se mi hodí, potřebuju trocu spravit náladu po konfliktu s detmi:-)
