### ISSUE TITLE
Vytvořit pořádnou sekci o týmu

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-cz#351]
Aktuálně je odstavec o týmu poměrně strohý. Tj. například jednotlivé core členy nedohledáte přes Google jako asociované s faktaoklimatu.cz.
* Možná krátké profily a fotku core členů?
* Samostatná stránka?
* Na titulce zobrazovat jeden profil náhodného člena core tímu? (Aby byl někdo i na titulce, ale aby se tam střídalo více lidí.)

**Comment by kikinna** [comment]
Jsem za krátký popis + fotku. Dokáži si to představit jako samostatnou
stránku, tím, že to není hlavní obsah toho, co utváříme.
Jinak zatím moc nejsem za jeden náhodný profil člena na titulce. Pak to
stahuje víc pozornost na nás na úkor tématu klimatu. Což do budoucna možná
můžeme udělat, když nám to zapadne do naší komunikace.

Taky mě napadá, že až budeme mít sekci o týmu a rozjetý twitter, tak možná
by stálo za to potom představit členy týmu postupně na twitteru? Možná ne?
I dunno. Just a thought.

**Comment by mukrop** [comment]
Hotovo.
