### ISSUE TITLE
Sekce: "Co tato grafika přináší do diskusí" do textů

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#361]
Chceme explicitně napsat argumenty (mýty, které vyvrací)
jen bych byl velmi citlivý ve slovníku (např nepoužít slovo "mýtus" nebo "vyvrací" ale ministr Havlíček v rozhovoru řekl ... a tato infografika ukazuje kontext a souvislosti, konkrétně ... takže ... )

**Comment by tomas-psorn** [comment]
S @SklenarOldrich jsme si na setkní s experty povídali s Kubou, který psal nějaké texty, ve kterých vyracel mýty, které se často objevují v diskusích (mimo to říkal, že plánují vydat knihu). Z toho bych vyšel, podíval bych se, které z těch mýtů  pokrývají naše infografiky a zkusil k některým infografikám doplnit ty sekce. Oldo mohl by jsi sem dát nějaký odkaz na ten web o kterém mluvil? Nestihl jsem si poznamenat název. Děkuju.

**Comment by ondraspribyla** [comment]
Doplnuju rovnou, protože můžu :-)

https://www.czechsight.cz/author/jakub/

Doklikej si jeho texty

Dne po 27. 1. 2020 10:47 uživatel Tomáš Pšorn <notifications@github.com>
napsal:

**Comment by kikinna** [comment]
Hh, to je roztomilý, že už má na webu "člen týmu faktaoklimatu.cz" :D

**Comment by ondraspribyla** [comment]
souvisí s #566

**Comment by jankrcal** [comment]
Zablokované rozhodnutím (a naprogramováním) ohledně #566.

**Comment by ondraspribyla** [comment]
Tohle issue je staré a trochu vyoutované explainery, snahou přestrukturovat web apod... zavírám.
