### ISSUE TITLE
Text k datové sadě: Teploty

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#380]
- [ ]  popis co sada obsahuje

- [ ] případně odkaz na nějaké standardy mměřicích metod ČHMU

**Comment by jankrcal** [comment]
Next steps:
 - dostat z Marka zárodky textu, příp. zjistit, že nic takového neexistuje
 - sepsat, co zvládnu sepsat

**Comment by ondraspribyla** [comment]
Zárodek informace od Michal Žák MFF UK: průměrná teplota v ČR je počítána z
gridu (prý snad 500*500m) kde hodnoty pro jednotlivé gridove body jsou
počítány interpolací mezi meteostanice + je započítán reliéf... Nevím, zda
potřebujeme tuto podrobnost...

Dne ne 19. 7. 2020 10:59 uživatel jankrcal <notifications@github.com>
napsal:

**Comment by ondraspribyla** [comment]
Vzhledem k tomu, že Datasety nevypadají jako stěžení produkt bych tohle issue zavřel. Jestli @jankrcal  Jeňo nesouhlasíš, klidně ho znovu otevři ...
