### ISSUE TITLE
Čitelnost doprovodného textu

### ISSUE THREAD

**Issue by mgrabovsky** [faktaoklimatu/web-cz#415]
Texty pod infografikami aktuálně příliš nelákají ke hlubšímu čtení, protože jsou příliš dlouhé a přehuštěné. V současné situaci mají řádky délku kolem 150 znaků, což je dvakrát víc než doporučených 60–75 znaků a zejména delší texty se nečtou moc příjemně.

Srovnejme aktuální vzhled

![Screenshot_2020-02-18 Elektřina v ČR výroba, spotřeba a emise(1)](https://user-images.githubusercontent.com/134321/74779771-76395280-529e-11ea-9821-d54907fae030.png)

a stav po pár drobných úpravých – rozdělení na dva sloupce, odstranění odrážek, zvětšení mezer za odstavci a o kapku vyšší řádky

![Screenshot_2020-02-18 Elektřina v ČR výroba, spotřeba a emise(2)](https://user-images.githubusercontent.com/134321/74779785-79ccd980-529e-11ea-9984-107d9d77fdd6.png)

Podle mého je druhé rozložení esteticky příjemnější a mnohem čitelnější, zejména pokud je textu hodně. Jedná se jenom o hrubý nástřel (pár rychlých úprav CSS), jak by mohl vypadat optimálnější stav, který je k diskuzi a k testování.

**Comment by kikinna** [comment]
@mgrabovsky 
Super, že to píšeš a vidíš tento problém)
Toto je téma, které se bude řešit (brzy) i v souvislosti s tištěním grafik a textů k tomu, kde budeme promýšlet jasnější strukturu a narativ. (Tak jak to je to není dostačující pro doplnění k tištěné grafice.) A ty změny by se měly odrazit i na webu.
Na webu to je zatím využíváno jako doplňující informace spíš než souvislej text / článek.
Imo, teď bych to na webu neupravovala vizuálně, protože na to není ready obsah. Jakmile máš odstavcové, ala článek, čtení, je potřeba, aby to mělo jasnou a navazující strukturu. Chce tam taky řešit hierarchii informací (ne každý chce číst celý článek, ale může ho zajímat shrnutí v prvním odstavci) atd. Tudíž bych to řešila dohromady s tím tiskem.
Dává to takhle smysl?

Ale ráda bych tě zahrnula do týmu lidí, co budou řešit podoby textu dál. Bylo by to něco, co by ti přišlo zajímavé?

**Comment by mukrop** [comment]
No, mne osobne sa prva verzia zda lepsia ako druha :-P (ale viem, ze v tomto asi nebudem priemerna vzorka a Matejov format bude asi mnohym ludom vyhovovat).

Kazdopadne suhlasim s Kikou, ze to chce prerobit strukturu textu viac nez len vizual. Navrhujem teda, aby si koncepcnejsie veci riesil s Kikou, ak mas zaujem. Ak mas navrhy na konkretne drobne vylepsenia (napriklad upravu odsadzovania odstavcov), tak klusne nadhod PR s upravami CSS (sam vidim, ze tam je co zlepsovat). Do dvoch stlpcov prosim zatial nepodme, nechajme to az na tu koncepcnejsiu upravu.

**Comment by mgrabovsky** [comment]
OK, to zní dobře. Nevěděl jsem, že jsou v plánu takové věci. Taky jsem to myslel spíš koncepčně a tohle mělo sloužit jenom jako příklad, jak se toho dá s málem hodně zlepšit (subjektivně :]), pročež issue a ne PR. Zapojím se tedy do plánování, jakmile bude možnost, a implementaci zatím nechávám stranou.

**Comment by ondraspribyla** [comment]
souvisi s #566

**Comment by mukrop** [comment]
Beriem sa hotovo :-).
