### ISSUE TITLE
Přidání do zdrojů: EU consilium 

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#433]
https://www.consilium.europa.eu/cs/policies/climate-change/

O webu: web poskytuje souhrnné informace o institucích a politikách EU. Daná podstránka udává přehled toho hlavního, co se na nejvyšší evropské úrovni děje v otázkách klimatu.

**Comment by ondraspribyla** [comment]
assigned to Filip Kessner

**Comment by jankrcal** [comment]
Ondráši, odstranil jsem Tě jako assignee, aby bylo jasnější, že to je free-to-take.

**Comment by ondraspribyla** [comment]
Zavírám. Not relevant.
