### ISSUE TITLE
Globální a Evropské dohody týkající se klimatu

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#434]
https://docs.google.com/document/d/1EQnmnw7CQ6272__h8MrI2GEzxkBrOGtlez0IEIy40Ic/edit?usp=sharing

**Comment by kikinna** [comment]
Aktuální stav
![Mezinarodni klimaticke dohody-01](https://user-images.githubusercontent.com/11555522/94987082-e06be280-0563-11eb-8252-a4d8c7b35637.png)

@katkolouchova Btw, ta druhá timeline

**Comment by protivinsky** [comment]
Ahoj, připravuji PR k této grafice - mám k dispozici verzi 8, ale z komunikace mezi Luckou a Ondrášem jsem pochopil, že to ještě není finální (a tuším, že Lucka posílala začátkem tohoto týdne Kristi nějaké změny, které je potřeba udělat),

@kikinna je to tak? Jde mi především o tom, abych měl představu, v jakém je to stavu a jestli se to posouvá. Připravím pro PR zatím ostatní věci a až bude hotová grafika, můžeme zveřejňovat.
