### ISSUE TITLE
Domluvit systém verzování infografik a datasetů

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-cz#478]
- [ ] udělat systém, jak psát ke grafikám a datasetům historii (jako nice-to-have by to časem mohlo autogenerovat kus obsahu do news a do newsletteru, ale to rozhodně nemusí být teď)
- [ ] sepsat ke každé infografice a datové sadě rozumnou aproximaci dosavadní historie (nemusí být dokonalé)
  - [ ] [Martin] Nahodit datovy subor `_data/changelog.yml` v ktorom sa info o zmenach bude pisat pre vsetky datasety a infografiky (stranky si to potom budu vyberat podla slugu).
  - [ ] Preklopit tam changelog infografik, ktory spracovaval minule crysman s Kristy
- [x] aktualizovat všechny grafiky, verzi zpětně datovat k poslední obsahové změně
- [ ] [Jeňa] vymyslet, jak v samotném Google Sheetu: 
   - udávat verze,
   - odkazovat na stránku datasetu (pokud existuje) a
   - komunikovat, pokud je dataset neaktuální.
- [ ] Udělat úpravy ve všech datasetech (možná spojit s řešením #468)

------ Původní text issue:

Je treba to verzovanie dohodnut, uz nam na tom visia viacere veci (#467, #266, ...).

Kedze prevazovanie a major-minor verze sme minule nevymysleli k nasej spokojnosti a planujeme urobit _changelog_ k infografikam aj datasetom, navrhujem verzovat datumom (tj. pisat nieco ako "verze: 2020-04-16", teda datum poslednej modifikacie).
* Previazanie na datasety podla mna nebude nutne, pretoze v _changelogu_ datasetu sa bude dat dohladat, ake zmeny sa stali od daneho datumu.
* Je to univerzalne, vsetko sa da verzovat datumom.
* Nevyhoda 1: Znamena to zmenit system verzovania na existujucich grafikach.
* Postreh: Bude potom na stabilnych grafikach jednoduhsie vidno, ze su napr. rok–dva bez zmeny (ale to mi nepride ako nutne zle).

Co si o tom myslite? @ondraspribyla, @jankrcal, @kikinna

**Comment by jankrcal** [comment]
Mně se to líbí.

Je to méně strukturované, než současné schéma verzování grafik, ale podle mě tuto strukturu nepotřebujeme.

Jediná věc na zvážení pro mě je, jestli máme ambice rekonstruovat podstatné změny (např. opravy chyb) u vybraných grafik i v minulosti, nebo jestli začneme changelogy s čistým štítem.

Za sebe si nejsem jistý, ale přijde mi trochu divné všechny grafiky teď overzovat současným datem, tak bych jako minimální variantu aspoň v gitu dohledal, kdy byla která grafika změněna naposledy.

**Comment by mukrop** [comment]
Na tie zmeny sme sa divali s @kikinna uz pred nejakym casom, pri mnohych inforgafikach jednoduchy changelog v textovej podobe existuje u grafikov (a existuju aj stare verzie, takze z gitu sa to da lahko dohladat cez historiu – a podla mna by to stalo za to).

**Comment by jankrcal** [comment]
Ok, souhlasím s jistou základní archeologií.

Máme shodu na takovém verzování, můžeme rozplánovat do next steps?

**Comment by kikinna** [comment]
Datovat to je dost zajímavej přístup. A vlastně proč ne. 
Koneckonců, čtenáři tak či tak nic neřekne ani datum, ani verze, pouze až v porovnání s něčím dalším.
Takže asi jsem za. 
(Jinak teda taky vnímám to, že grafika se dva roky starým datumem může působit staře.)

Jinak já mám ke všem grafikám a exportům data. Takže bych byla za na všechny grafiy dát datum posledního exportu (předt touto úpravou).

**Comment by jankrcal** [comment]
Supr, rozepsal jsem next-steps, klidně upravujte.

**Comment by mukrop** [comment]
Nahodim format a potom asi poprosim crysmana, aby to doplnil datami (on minule konsolidoval prehlad vsetkych zmien infografik).

**Comment by crysman** [comment]
v rámci #464 aktuálně probíhá překlopení na systém "isodatum" ala 2020-10-03

**Comment by mukrop** [comment]
@jankrcal, aky je stav tohto?
* Grafiky su uz myslim vsetky preverzovane.
* Mame vymyslene, ako verzovat datasety/studie/explainery? (Stoji to za to vobec robit?)
* Changelogy mame v inom issue, tie by som tu uz neriesil.

Myslim, ze toto issue by sa asi mohlo aj zavriet, ale nechavam na zvazenie este tebe. (Pripadne zavriet a urobit samostatne issue k datasetom.)

**Comment by jankrcal** [comment]
S datasetama není progres, nemělo to prioritu / čekalo se, až budou udělané grafiky.

Nechal bych otevřené, přejmenuju na zachycení užšího scope.

**Comment by jankrcal** [comment]
A nebo ne, založím si vlastní issue.
