### ISSUE TITLE
Udělat první infografiky zaměřené přímo na sucho

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-cz#499]
Souvisí s #496, v rámci které nejspíš vznikne myšlenková mapa souvislostí ohledně sucha.

Další kroky:
- [ ] Ondráš: při hovoru s experty zjistit, jaké jsou dostupné metriky / datasety, které by bylo zajímavé zobrazit.
- [ ] Jeňa: pročíst novou publikaci o zemědělském suchu s ohledem na zajímavé dostupné metriky / datasety: https://www.intersucho.cz/userfiles/file/ZemedelskeSucho.pdf

**Comment by ondraspribyla** [comment]
S michalem Žákem jsme volal dneska. Rámcově je to v pořádku, několik updatů
jsem udělal přímo do muralu.
Použitelná data ale přímo nemá, zkusím je dostat z CzechGlobu.

O.

**Comment by jankrcal** [comment]
Publikace Zemědělské sucho (https://www.intersucho.cz/userfiles/file/ZemedelskeSucho.pdf) ukazuje zajímavé indexy v kapitole 2.1, konkrétně SPEI (Standardizovaný srážkový evapotranspirační index) v Obr. 12. Zdroje dat neodkazují, ale očividně to někdo měří / odhaduje, tak bychom se k tomu měli dostat.

Ještě mi přijde zajímavej Obr 7. (suma ročního přímého slunečního záření) jakožto možný mezičlánek mezi "je tepleji" a "víc se vypařuje".

**Comment by ondraspribyla** [comment]
Přehazuju do knowledge base do Notionu... sucho letos asi nebude silný téma. zavírám.
