### ISSUE TITLE
Změnit logo v hlavičce webu

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web-cz#517]
Na [drive](https://drive.google.com/drive/folders/1_RALqcZYwxMKISWz6UYPV-Lx2P0Gt3eR) máme už naše logo, které dáváme od Open Data Expo na ofiko materiály, tak by bylo fajn ho dát i na web. Jen si nejsem jistá, jak se vejde / bude čitelné v panelu, ale to chce asi ozkoušet.
(Respektive udělat jednořádkovou variantu?)

**Comment by mukrop** [comment]
Ano, prosim o jednoriadkovy variant :-).

**Comment by mukrop** [comment]
Par postrehov k tomu:
* Aktualne logo ma font od Arobatu, prejst radsejna Free Sans Pro (pouzivame ho aj na webe).
* Aktualna verzia by bola v hlavicke prilis tazka.

Nechavam na rozmyslenie do buducna, rusim drobnost aj free-to-take.

**Comment by mukrop** [comment]
Zatvaram. Ak to bude relevantne, otvorime znova v buducnosti.
