### ISSUE TITLE
Odkaz na Carbon Brief

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#518]
Přidat Carbon Brief mezi https://faktaoklimatu.cz/zdroje.

**Comment by jankrcal** [comment]
Chápu to správně, že chceš přidat tento web mezi https://faktaoklimatu.cz/zdroje?

**Comment by ondraspribyla** [comment]
Carbon Brief určitě mezi zdroje. Mapu světových uhlených elektráren stojí za to citovat jako jeden z odkazů, stejně tak mají skvělé explainery klimatických modelů, množství požárů a dalších souvislostí. 

Přemýšlel jsem, že by se možná odkaz na mapku hodil někam do našich stránek, aby si uživatel mohl dokliknout kde jsou největší HU elektrárny... ale zatím mě nenapadá vhodné místo. Snad jen že bychom vytvořili českou mapku HU elektráren (a případně dalších emitentů podle emisních povolenek.

**Comment by jankrcal** [comment]
Protože mapka hlavních emitentů ČR je v plánu na víkend, tak toto issue omezuju na přidání Carbon Brief mezi https://faktaoklimatu.cz/zdroje.

Původní odkaz https://www.carbonbrief.org/mapped-worlds-coal-power-plants mi přijde jako skvělá věc do doprovodného textu ke grafice hlavních emitentů. Máme na to issue, že bych to tam přesunul?

**Comment by ondraspribyla** [comment]
Odkazy nepoužíváme, tak bych tohle issue zavřel... v textu k největším emitentům už odkaz doplněný je. Zavírám.
