### ISSUE TITLE
Grafika: Sucho v ČR

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web-cz#521]
Tento graf mi přijde hodně působivý:

![image](https://user-images.githubusercontent.com/9573993/81796713-bc046080-9505-11ea-8006-b9b2a49362fc.png)

Stálo by za to zpracovat něco podobného?
Zdroj https://www.intersucho.cz/ zatím ale navím na jakých přesně datech je to založené.

**Comment by kikinna** [comment]
Nevím, co je PDSI, ale graf je dobrej. ))

**Comment by protivinsky** [comment]
Jo, já to taky nevěděl - http://stavsucha.cz/about-indicators/

> Palmerův index intenzity sucha PDSI (Palmer Drought Severity Index; Palmer, 1965) představuje jiný přístup k hodnocení sucha a je celosvětově široce aplikován ke kvantifikaci sucha. Jeho výpočet vychází z vodní bilance studovaného území, která zahrnuje úhrn srážek za sledované období (typicky jeden měsíc), aktuální obsah vody v půdě a výdejovou evapotranspirační složku (potenciální evapotranspirace PET). Pro účely portálu stavsucha.cz, je využívána metoda dle Penman-Monteithe v modifikaci dle Allena et al. (1998), kterou využívá i model SoilClim. Wayne Palmer vyšel z předpokladu, že půdní profil je možné redukovat na dvě vrstvy – svrchní ornici a spodní vrstvu kořenovou. Dokud není orniční vrstva plně nasycena vodou, nedochází k prosakování vody do hlubší vrstvy. Povrchový odtok je do výpočtu indexu zahrnut až v okamžiku, kdy jsou obě půdní vrstvy nasyceny na hodnotu maximální retenční kapacity a zároveň je pokryt výdej vody evapotranspirací v příslušném měsíci. Protože PDSI reprezentuje kumulativní odchylky v přebytku nebo nedostatku vláhy na povrchu s ohledem na průměrné poměry dané lokality, může být vhodným indikátorem epizod dlouhodobého sucha.

**Comment by jankrcal** [comment]
Pěkný, jsou k tomu zdrojový data?

Souvisí s #499 a s #496, konkrétně vytahuju přemýšlení Ondráše a mě nad souvislostmi sucha:
https://app.mural.co/t/zengarden9550/m/zengarden9550/1585601355120/6188fa9f7f70ada4aa003203a7452b48704440ce

**Comment by setcz** [comment]
Tohle na mě bliklo dnes na fb a připadá mi to dobrý, jak to ukazuje nesmyslnost nových přehrad - https://infogram.com/krajina-versus-prehrady-1h8n6md39pnz6xo?live

**Comment by jankrcal** [comment]
Pěkný!

Jen mi to přijde zlehka demagogie :)

Jakože v kategorii "zadržení vody v krajině" to je férové. V kategorii "zdroje pitné vody" (což chápu, že je motivace nových přehrad) mi to nepřijde férové srovnání, protože není jasné, kolik z té vody, kterou navíc zadržíš, můžeš pak navíc vypít. Ona velká většina nepochybně zahučí v evapotranspiraci. Kolik to ale je, to netuším...

**Comment by protivinsky** [comment]
Letmo jsem se po datech podíval a nenašel, napsal jsem jim přes twitter, kde tento graf sdíleli. Mimochodem mají k suchu novou publikaci (nicméně tento graf jsem v ní nezahlédl): https://www.intersucho.cz/userfiles/file/ZemedelskeSucho.pdf
- možná by stálo za to ji zpracovat do studií?
- kromě toho je tedy jejich kapitola o příčinách sucha do velké míry založená na našich infografikách :)

Evapotranspiraci odhaduje nahrubo Jiri Hlavenka zde: https://ekolist.cz/cz/publicistika/nazory-a-komentare/jirin-hlavenka-komentar-k-silenemu-napadu-ministerstva-zemedelstvi-postavit-31-novych-prehrad - nejspis je to nadsazene, ale kazdopadne to vede k zamysleni:

> Něco čísel. Česká krajina zadrží o tři miliardy (3 000 miliónů) kubíků vody méně než by mohla, pokud by se hospodařilo zdravě. Všechny nově plánované přehrady DOHROMADY zadrží při maximálním stavu 200 mil. kubíků (viz druhý odkaz).
> Nedosti na tom. Volná vodní hladina má taky nemalý odpar. Plocha 10 x 10 metrů odpaří průměrně ročně 700 kubíků vody. Nové přehrady mají mít dohromady plochu 30 km2 (3000 hektarů). Moje kalkulačka říká, že roční odpar z této plochy je 210 mil. kubíků. Povšimněte si laskavě praktické shody s číslem v předchozí odrážce (kalkulace odparu z vodní hladiny).

**Comment by protivinsky** [comment]
Trochu mě překvapuje, že ten upgrade je odlišný od původního grafu (a nejen kvůli mnohem časové delší ose). Informace o datech je pořád trochu vágní, ale počítám že od CzechGlobe bychom nějak byli schopni je získat.

> Kousek výš máme ugrade toho grafu i se zdrojem, vzbudil docela pozornost a právě proto jsme ho protáhli na celou dobu přístrojových měřen a ozdrojovali. Je to z dat CHMU a vypočteno námi, tedy na CzechGlobe.

![image](https://user-images.githubusercontent.com/9573993/82024258-6b1c7580-9687-11ea-84d5-32fffb4dc015.png)

**Comment by ondraspribyla** [comment]
asi bych to uzavřel... pokud se vrátíme k tématu sucho, najdem to v closed issues...
