### ISSUE TITLE
Studie: 80% snížení emisí skleníkových plynů v ČR

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web-cz#533]
Draft: https://docs.google.com/document/d/19zAmgCCwn5FCXyz-FUsn53VHl0Y-gmCZkl5SYpPv4Uo/edit

@ondraspribyla uvítám případné komentáře / návrhy. Zejména v několika místech si nejsem jist, zdali se ohledně plánů ČR něco nezměnilo, kdybys náhodou věděl.

**Comment by ondraspribyla** [comment]
Ohledně plánů ČR vlastně neví, dosud jsem to nesledoval. Přidal jsem pár
poznámek, ale  podstatě souhlasím s Jeňou... + nevím jak je na tom záměr EU
být do 2050  uhlíkově neutrální...

Jinak obdivuji tvoji práci, někdy bych si od tebe nechal dát o této studii
nějkou přednášku, protože modelování ekonomiky a diskontování vlastně vůbec
nerozumím...
Díky.
O.

**Comment by jankrcal** [comment]
@protivinsky Tome, v jakém je to stavu? Má smysl tuto studii dotáhnout, když už je dávno po tiskovce?

**Comment by protivinsky** [comment]
Smysl dotáhnout to určitě má:
- je to zajímavé a především v kontextu ČR
- hodí se to i strategicky, jednoho z autorů bych rád do vědecké rady a think tank IDEA je obecně zajímavá organizace i z hlediska případné spolupráce

Po tiskovce jsem to trochu odložil, pustím se znovu do toho. Jde především o zjištění, do jaké míry se změnily strategické dokumenty a plány na úrovni ČR / EU + dotažení textu dle komentářů.
