### ISSUE TITLE
Přidat Cranky Uncle do knih

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-cz#535]

**Comment by jankrcal** [comment]
Martine, přesunul jsem na víkend do free-to-take. Pokud trváš na osobním odvedení této práce, tak se prosím znovu přiřaď :)

**Comment by ondraspribyla** [comment]
Odkazy se takto asi reálně používat nebudou... časem možná můžeme udělat rešerši "Knihy o klimatu" - Issue zavírám
