### ISSUE TITLE
opravy drobných textových chyb

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web-cz#554]
### 1) je třeba opravit věci typu "v loňském roce", např. zde:
http://localhost:4000/infografiky/elektrina-cr

tu je celkový výpis:
```
✔ ~/faktaoklimatu.cz/gitfolder/faktaoklimatu [crysman-revizeTags|✔] 
21:59 $ grep -iRIEH "loňsk|loni|minulém|minulým|letos|letošní" ./ --exclude-dir=.cache| awk -F':' '{print $1}'
./_infografiky/emise/elektrina-cr.md
./_infografiky/opatreni/zpoplatneni-emisi-svet.md
./_studie/2020_globalni-zprava-o-elektrine.md
./_site/infografiky/zpoplatneni-emisi-svet.html
./_site/infografiky/elektrina-cr.html
./_site/assets/infographics/elektrina-na-osobu-svet.svg
./_site/studie/2020_globalni-zprava-o-elektrine.html
./_site/temata/energetika/index.html
./assets/infographics/elektrina-na-osobu-svet.svg
./_data/tags.yml
```

tj.

- [ ] ./_infografiky/emise/elektrina-cr.md
- [ ] ./_infografiky/opatreni/zpoplatneni-emisi-svet.md
- [ ] ./_studie/2020_globalni-zprava-o-elektrine.md
- [ ] ./_site/infografiky/zpoplatneni-emisi-svet.html
- [ ] ./_site/infografiky/elektrina-cr.html
- [ ] ./_site/assets/infographics/elektrina-na-osobu-svet.svg
- [ ] ./_site/studie/2020_globalni-zprava-o-elektrine.html
- [ ] ./_site/temata/energetika/index.html
- [ ] ./assets/infographics/elektrina-na-osobu-svet.svg
- [ ] ./_data/tags.yml

### 2) další random chyby co jsem zahlédl:
- [x] http://localhost:4000/infografiky/emise-svet-na-osobu : 
![image](https://user-images.githubusercontent.com/5269350/83297269-8bedda80-a1f2-11ea-8bfa-c5de76500e74.png)
- [x] http://localhost:4000/infografiky/emise-cr-detail
![image](https://user-images.githubusercontent.com/5269350/83298014-f94e3b00-a1f3-11ea-96d8-8745625f60a9.png) -> jako

**Comment by crysman** [comment]
@kikinna přidal jsem i KIku, lebo je to přímo v grafice

**Comment by jankrcal** [comment]
@crysman Crysmane, díky za report! Rozděluju na dvě issue:
 1) jazykové korektury nových infografik (kde je potřeba Tvoje / Lenčina expertíza),
 2-4) free-to-take issue na opravení drobných chyb, to může zařídit / udělat kdokoliv na klimatonu.

Pokud bys s tím nesouhlasil, tak prosím protestuj.

**Comment by crysman** [comment]
@kikinna v infografikách už nic k opravě nevidím, můžeš se odsud oddělat

**Comment by crysman** [comment]
nečetl jsem to ještě ale zahlédl jsem to tu taky
https://faktaoklimatu.cz/explainery/zpravy-ipcc - nejméně 5 výskytů 
![image](https://user-images.githubusercontent.com/5269350/130760880-6541a6b1-e1d5-48b6-91aa-211a49039e5e.png)

podle mě musíme buď (XOR):
a) normálně to používat, ale mít funkční watchdog na tato slova a odchytávat to + nějaký event na 1.1. každého roku na fix
b) blbuvzdorně to nepoužívat vůbec a držet se striktně formulací "v roce 2021" atp.

co vy na to? @Jirka-tisnov

**Comment by crysman** [comment]
neaktuální thread, zavírám
aktuální zde: https://github.com/faktaoklimatu/web-cz/issues/1049
