### ISSUE TITLE
Zlepšit "udržení" návštěvníků na webu

### ISSUE THREAD

**Issue by setcz** [faktaoklimatu/web-cz#571]
Koukal jsem do Google Analytics a jedno zjištění je - když lidi dorazí na konkrétní infografiku, často už se pak nepodívají nikam jinam. Stálo by myslím za to vymyslet jak lépe udržet lidi na webu, když dorazí na konkrétní infografiku.

### Data:
Pouze asi 40 % návštěvníků přijde na náš web na homepage.
Většina, asi 60 %, dorazí přímo na nějakou konkrétní infografiku.

Ti, co dorazí na homepage, tak z 57 % odpadnou rovnou.

Ti co dorazí na konkrétní infografiku, tak z 80 - 90 % odpadnou rovnou.

Část se dá asi vysvětlit tím, že si lidi najdou, pro co si přišli a jdou pryč. Nicméně myslím, že bychom mohli zapracovat na jejich udržení.

### Nápady, co s tím:
(přidávejte další)
- upravit text "Zaujala vás tato infografika? Zde je pár náhodně vylosovaných ze stejné kategorie:" - na mě působí jako "whatever, nechce se nám to řešit, tady jsme ti něco hodili" - návrh něco jako "Zaujala vás tato infografika? Prozkoumejte další podobné:"
- Přidat pod ty vylosované infografiky ještě odkaz typu "Nebo se podívejte na [přehled všech infografik](faktaoklimatu.cz).", který povede na homepage

**Comment by ondraspribyla** [comment]
@setcz přemýšlím nad tím, co píšeš... 

- změna wordingu a link na hlavní stránku podle tvých návrhů mi dává smysl, protože zatím jediný link ze stránky grafiky na hlavní stránku je přes horní MENU-ÚVOD ... Mohli by se na to prosím podívat @mukrop nebo @mgrabovsky ? Ti budou vědět kde co změnit a jak přidat link na hlavní stránku. (Mě by přišlo nejlepší změnit wording na "Zaujala vás tato infografika? Prozkoumejte další podobné:" + pod náhodný výběr přidat odkaz na hlavní stránku "Nebo se podívejte na přehled všech infografik."

- chybí mi info o tom kdo jsou lidi, kteří odpadají a proč. Myslím, že pro většinu lidí nejsme ideální zdroj a nepotřeujeme je tedy udržet - důležité je, zda jsme vhodný zdroj pro učitele, novináře, nebo klimatické laiky... i tak myslím bude mnoho motivací, proč se daný člověk na naši stránku dostal: - protože chce něco konkrétního?  - protože náhodně browsuje v rámci témat a jiná stránka ho sem odkázala? - protože klikl na post na twitteru?  

Odpověď na otázku, zda můžeme naše stránkky vylepšit a jak, bych hledal spíše v živém testování nebo přímém dotazování na lidi z cílovek ("co byste na stránkách chtěli?")
a čekal bych, že největší benefit přinese 
- přehlednost stránek i orientace v tématech grafik (máme už přes 40 grafik/studií a další budou přibývat)
- přehlednost textu ke grafikám (nejspíš rozbalovací pole, aby člověk jedním pohledem viděl obsah a nemusel scrolovat dolů aby našel třeba metodiku nebo komentář... ale i změna stylu)
- odpovědi na konkrétní potřeby skupiny uživatelů - např prolinkování na učitelské metodiky, které ukazují jak použít konkrétní graf ve výuce.

**Comment by kikinna** [comment]
Toto je dost velký téma (a čas od času se někde zmíní design webu -
nemyslím vizuální, ale obsahový+uživatelský).

Jsem za to udělat nějaký rewording, ale myslím, že by stálo za to pořešit
(až bude prostor, případně finance) redesign webu a ideálně konzultovat už
se zkušeným UXákem. (Přijde mi to nice cíl na rok 2021, co myslíte?)
Jen na to potřebujeme mít jasně vydefinované otázky cílovky a způsobu
použití pro ně.
Zároveň i do nějaké míry produkty/služby (e.g. games4sustainability)

Zatím mám dojem, že to spíš jen lepíme, ale imho je ten web už trochu
kostrbatý. (Pro teď, vzhledem k našim omezeným kapacitám, to nevnímám jako
klíčové, ale profesně a dlouhodobě to je za mě potřeba předělat)

Možná je to téma na víkendovou chatu / board, jestli to budeme chtít
adresovat?

**Comment by jankrcal** [comment]
Souhlasím s tím, že solidní redesign je velký téma. 

Nemyslím si, že to je to, do čeho bychom měli investovat čas na nejbližší chatě. Podle mě jsou jiný věci, co potřebujeme posunout, zatímco web zatím docela funguje.

Jsem pro zatím dělat malý iterativní vylepšení a s větším redesignem počkat, až budeme mít jasnější cílovky a critical user journeys (snad druhá půlka 2021?).

**Comment by mgrabovsky** [comment]
Téma použitelnosti webu mi leží v hlavě a na srdci už delší dobu. Několikrát jsem zmiňoval, že je web na můj vkus už trochu přeplácaný a příliš poslepovaný, a silně souzním s tím, že redesign je potřeba.

Nemám zkušenosti s webovou analytikou, takže nedokážu odhadnout, jak moc je 57 % odpadnutí z homepage, ale 80 % z konkrétní infografiky se mi zdá zbytečně hodně. (Samozřejmě by bylo zajímavé se podívat i na časy strávené na stránkách, popř. cesty těch, co hned neodpadli, odkud obecně lidi přicházejí atd.) Nejsem si jistý, jestli je tohle známka, že „web zatím docela funguje“. Nicméně jsem se s nikým „zvenku“ o webu nebavil, takže soudím čistě z vlastních, subjektivních dojmů.

Jak píše Kristi, nejde (jen) o „redesign“, o vizuální stránku nebo volbu slov – je potřeba se zamyslet nad celou informační architekturou. Taky souhlasím, že by stálo za to přenechat to výhledově profesionálům. (V souvislosti s #604: kolem Česko.Digital je vícero schopných UX lidí, se kterými by stálo za to aspoň konzultovat.)

Osobně mi přijde velmi důležité, aby web udělal dobrý první dojem (ne nutně perfektní) ještě předtím, než se nějak „etablujeme“. Nejednou se mi stalo, že jsem z první návštěvy nějakého webu nebyl příliš nadšený a pak jsem ho dlouhou dobu ignoroval jenom kvůli tomu špatnému prvnímu dojmu. (A nejednou jsem litoval, že jsem mu nedal druhou šanci dřív.) Sám teď nedokážu spolehlivě odhadnout, kolik bych na FK strávil času, kdybych už předtím neměl o téma _značný_ zájem.

Zároveň si myslím, že tu máme i pár „low-hanging fruits“, které by za vydání relativně malého úsilí značně zvýšily použitelnost a přívětivost. Ondrášovy návrhy mi dávají smysl. Asi by i stačilo zeptat se na názor pár náhodných lidí.

Já sám jsem nedávno přemýšlel nad hlavní stránkou. Obecně jsem názoru, že čím víc relevantních, dobře zpracovaných grafik a textů, tím líp. Taky je dobře mít je někde všechny najednou. Tím místem ale nemůže být uvítací stránka pro 40 % lidí. Osm grafů v malých sekcích vypadá OK. 30 infografik, osm studií a pět datasetů na jedné (zejména té první) stránce už je moc. Zahlcení a bezradnost, kam zaměřit pozornost, nepatří mezi první dojmy, které bych chtěl vyvolávat u potenciálních návštěvníků, ať už je cílovka jakákoliv.

---

@ondraspribyla Na hlavní stránku se dá dostat i kliknutím na „Fakta o klimatu“ v navigační liště, což je vcelku tradiční cesta. Nejsem si jistý, jestli přidání dalšího odkazu někam jinam prospěje. Větší smysl by mi dávalo „polidštit“ odkazy na související grafiky/další zdroje nebo líp prolinkovat ostatní části webu.

**Comment by ondraspribyla** [comment]
Odkazy na grafiky jsou nyní jako náhledy součástí textu... beru to jako postupné vylepšování webu a asi budeme časem předesignovávat... přijde mi ale zbytečné držet tohle jako issue, takže uklízím a zavírám
