### ISSUE TITLE
Vyrobit mapku uhelných elektráren v ČR

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#581]
Problém = lidé neví, kde jsou uhelné elektrárny a kolik emisí produkují.

Možná by šlo vyjít z tohoto:
https://www.carbonbrief.org/mapped-worlds-coal-power-plants

Možná by nemuselo jít jen o elektrárny - přehled podniků, s potvrenými emisemi za rok 2016 je zde:
https://faktaoklimatu.cz/datasety/emise-cr
---------
Tedy asi jako výstup by byla dobrá mapka s umístěnými ikonami emitentů podle typu (elektrárna/průmyslový podnik). Velikosti asi nejde říct jasně (data z 2016 jsou stará) šlo by šedě zobrazovat ty elektrárny, které už jsou odstavené.

**Comment by jankrcal** [comment]
Jen dodávám, že tato data z ETS jsou k dispozici i za rok 2017, v průběhu roku (podzim?) by se měla objevit i za rok 2018.

**Comment by vlckel** [comment]
V Carbon Brief mají odkaz na zdroj dat, nicméně ta tabulka tam neobsahuje jak souřadnice nebo adresu, tak ani potvrzené emise. 
Data z ETS jsou na tom podobně a taky nemají geolokalizaci jednotlivých podniků.


**Alternativa**:
- Databázi elektráren ve světě (název elektrárny, souřadnice, kapacita) stáhnout odsud:
[](https://energydata.info/dataset/world-global-power-plant-database-2018)
- Potvrzené emise (z ETS) k elektrárnám ručně připojit podle jména zařízení. Pokud bude jenom ČR, ta ruční práce by nemusela být na moc dlouho.

**Comment by mgrabovsky** [comment]
Přes Developer Tools se dá dostat i k podkladovým datům ve formátu GeoJSON: https://global-coal-map-2020.s3.eu-west-2.amazonaws.com/data/coal2020.geojson

**Comment by vlckel** [comment]
To je super! Díky!

**Comment by ondraspribyla** [comment]
Resolved.
