### ISSUE TITLE
Explainery jako součást webu? 

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#605]
Opakovaně narážím na to, že některé pojmy, které se v oboru používají by stálo za to vysvětlit podrobněji, než je máme vysvětlené ve slovníčku. Zároveň ale kvůli tomu nechci vytvářet novou grafiku...

Carbon Brief píše články, které nazývá "explainery" viz archiv explainerů: 
https://www.carbonbrief.org/category/in-focus/explainers

Dává mi smysl psát i takové články, myslím, že ke zkvalitňování diskuse o klimatu a a opatření by to přispělo. 
Zároveň mi to dává smysl z hlediska workflow - je jednodušší nejdřív udělat analýzu a napsat na ni text a až teprve pak se snažit vytvořit grafiku (protože tvorba grafiky je v procesu úzké místo nejen kvůli vytížení Kristi, ale i kvůli tomu, že spousta grafik se zasekne na tom, že sdělení je moc komplexní...)
Zároveň některé články z Carbon Breifu bychom mohli prostě přeložit (mají to skvěle psané a přeložit je to jednodušší, než to psát, zvládne to i celkem nováček a bude to free-to-take)

Hlavní odázka je: kam s nimi na stránkách? 
Sekundární: ...měli bychom zkusit nekolik napsat a pak pro ně hledat umístění? Nebo zvolíme jiný proces vzniku?

**Comment by kikinna** [comment]
Já si myslím, že formát explainerů je skvělý formát a i "produkt", který
bychom chtěli dělat.
Souhlasím, že jsou témata, která nutně nepotřebují grafiku, ale přesto
potřebují adresovat. U toho mě napadá otázka, jestli je dobré mít primární
kategorizaci na webu podle formátu (infografika, studie, data, explainer)
nebo podle témat a významu (teploty, koncentrace, emise, atd.) a v těchto
kategoriích mít různé formáty - pokud chceme pomoci se v tématu
zorientovat, imho by dávalo smysl mít už web postavený podle obsahu, ne
formátu = typu zpracování informace.
V tom druhém případě bychom navíc byli i méně limitovaní aktuálně
používanými formáty a mohli bychom snadno zařadit nové/potřebné.

Nicméně zpět k explainerům - jsem za to to otestovat prvně a pak řešit kam
s tím: zkusit přeložit i zkusit napsat vlastní explainer. I kdyby to hned
nešlo na web, tak to tam určitě jednou bude a alespoň se otestuje, co k
tomu na tom webu budeme potřebovat.

Co se týče úzkého místa pro tvorbu grafiky - ano, teď je to úzké místo, ale
snad by za pár měsíců být nemuselo - tudíž bych byla opatrná s tím
navrhovat procesu na základě tohoto omezení (abychom kvůli kratší době
nepohodlí nenastavili kostrbaté procesy dlouhodobě).

To říkám hlavně i proto, že bych ráda silně podpořila tvorbu grafik a
explainerů (pseudo-)paralelně. Různé formáty podporují různou prezentaci
informací a inspirují různé otázky. A tak myslím, že je tyto různé pohledy
fajn zohlednit od začátku a docílit tím jaksi ucelenějšího uchopení tématu
a vyhnutí se situacím, kdy bychom potřebovali upravit explainer, protože se
u grafiky přišlo na to, že něco není jasný nebo by to téma mezi sebou
vzájemně nepodporovaly.
Je to teda můj pocit, můžu se mýlit.
Já bych navrhla s explainerem alespoň minimálně draftovat grafiku a bavit
se i s "designérem", který tématu potřebuje do nějaké míry taky rozumět a
slyšet, co je důležité, aby to zohlednil v grafice.

**Comment by ondraspribyla** [comment]
Draft explaineru k významu emisí z výroby cementu:
http://homel.vsb.cz/~khe0007/Predmety/Stavebni%20hmoty/Prednaska_c.6.pdf

**Comment by jankrcal** [comment]
Za mě souhlas dělit hlavní stránku podle témat a ne podle formátu informace
(to by podle mě pomohlo i studiím).

st 5. 8. 2020 v 11:23 odesílatel ondraspribyla <notifications@github.com>
napsal:

**Comment by ondraspribyla** [comment]
Jestli se v tomto chcete inspirovat u konkurence tak doporučuju prostudovat
jak témata člení ourworldindata

Dne st 12. 8. 2020 12:08 uživatel jankrcal <notifications@github.com>
napsal:

**Comment by mukrop** [comment]
@jankrcal, mozme toto issue zavriet?

**Comment by jankrcal** [comment]
Ano ano
