### ISSUE TITLE
Jak má ČR snížit emise podle Pařížské dohody?

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#613]
Cílem je skrze grafiku odpovědět na otázku "Jak moc má ČR snížit emise podle pařížské dohody" - nejspíše formou emisních scénářů pro 1,5°C a 2°C podle různých kritérií Equitability...

Kritéria představuje např.  http://paris-equity-check.org/ v sekci "Science". Zároveň v sekci Equity Map při kliknutí na ČR ukazuje emisní trajektorie podle různých kritérií... potíž je v tom, že ty emisní trajektorie počítají se snižováním emisí od roku 2010, nyní máme 2020 a dekáda bez snížení není započítána.

**Comment by ondraspribyla** [comment]
Napsal jsem mail na yann.rdp@climate-energy-college.org

Dear Mr. du Pont, 

I would like to use te data from http://paris-equity-check.org/ website both on our climate related website faktaoklimatu.cz and for a presentation and discussion in Czech senate we are going to have in September. However I have some questions I would need to clarify and I would appreciate your help

- The graph tool in http://paris-equity-check.org/multi-equity-map.html#open-graph uses the year 2010 as a reference point and for most countries the emission scenarios start falling right in the year 2010. However the current reality for Czech republic is that in 2010-2020 the emissions stagnated. For the presentation, we need to account for the period when our country (and perhaps most other countries)  kept the emissions staganting or rising. How would you recommend to adjust the data and calculations?

- Some of the emission scenarios require negative emissions in amounts -25% to -50% of their current emission rates. Is that feasible, technologically and economically?

- I would expect that a question of carbon budget for Czech republic would arise... would it be possible to get some data about carbon budgets for countries from your models? 

Thank you very much for your effort 
Best wishesOndras Pribyla

**Comment by kikinna** [comment]
@ondraspribyla Nepokryli jsme to dostatečně grafikou [Uhlíkový rozpočet ČR](https://faktaoklimatu.cz/infografiky/uhlikovy-rozpocet-cr)?

**Comment by ondraspribyla** [comment]
Jo, hotovo.
