### ISSUE TITLE
Aplikace rozbalovacích sekcí

### ISSUE THREAD

**Issue by mgrabovsky** [faktaoklimatu/web-cz#661]
Po [nedávné implementaci](https://github.com/faktaoklimatu/web/pull/657) rozbalovacích sekcí by bylo vhodné projít všechny naše dosavadní doprovodné texty a aplikovat tuto novotu v místech, která se zdají být přehuštěná nebo nepřehledná.

Použití je vcelku snadné. Stačí obalit blok, který chceme skrýt, do tagu `<details>` a nadpis umístit do tagu `<summary>`. Pro ilustraci přikládám použití z infografiky [potenciálu pro snížení emisí](https://faktaoklimatu.cz/infografiky/potencial-zpusobu-snizeni-emisi):
```html
<details markdown=1>
<summary>
<h3>Nalétáme polovinu vzdálenosti</h3>
</summary>

Letecká doprava odpovídá za přibližně 2,5 % světových emisí...
</details>
```

Rozbalovací sekce byly už aplikovány i v textu k infografice [adaptačních opatření ČR](https://faktaoklimatu.cz/infografiky/adaptacni-strategie-cr). Ostatní jsou zatím netknutné.

**Comment by ondraspribyla** [comment]
Začal jsem na tom pracovat, rozdělaná práce je ve větvi aplikace_rozbalovani

**Comment by mukrop** [comment]
Uz nerelevantne, mame TOC.
