### ISSUE TITLE
Aktualizovat údaje v grafice phase-out

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web-cz#663]
všiml jsem si, že tyto roky nesedí s [infografikou](https://faktaoklimatu.cz/infografiky/uhelny-phaseout-eu):
![obrazek](https://user-images.githubusercontent.com/5269350/95072295-42b31780-070b-11eb-9004-48c055a0b9a6.png)

PS: Portugalsko už máme backstage v nové verzi opraveno na 2021 (tak jsem si toho všiml, že jsem rychle proletěl ten text, esi netřeba opravit aj tam...)

**Comment by jankrcal** [comment]
Beru si to na sebe, nízká priorita.
https://faktaoklimatu.cz/infografiky/uhelny-phaseout-eu
