### ISSUE TITLE
Grafika: Schématická mapa systému 

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web-cz#673]
Nástřel mapy systému inspirovaná Fig 7.1: z There's no Planet B

_Velice hrubý draft grafiky_ s cílem začít se bavit o tom, co tam chceme, např. chceme jen velice minimalistickou mapu nebo chceme různé typy propojení (např. kódované barevně), což by byl mess, takže bychom mohli mít několik verzí grafiky. @ondraspribyla Nechceme si k tomu dát někdy pracovní / brainstorm session? 

![15 Koncepční mapa-04](https://user-images.githubusercontent.com/11555522/96467015-ca7c4400-122a-11eb-966b-e53b63e6df72.png)

**Comment by ondraspribyla** [comment]
Skoro hotovo - bude potřeba předělat texty v mapě.

**Comment by ondraspribyla** [comment]
Hotovo, zavírám
