### ISSUE TITLE
Udĕlat carousel úspěchů na titulce konfigurovatelný

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-cz#686]
Pravdepodobne cez datovy subor, tak ako altuality. Zvazit automaticku kontrolu pomeru stran/rozlisenia pouzitych fotiek, aby sa to nerozbijalo.

**Comment by jirkasemmler** [comment]
mame na to nejakej navrh (graficky) nebo aspon na papire? Technicky si to klidne vezmu, jen nevim jak to udelat hezky

**Comment by mukrop** [comment]
Ten cacousel uz existuje, vid https://faktaoklimatu.cz/#o-projektu.

Budeme tam ale teraz potrebovat ptidat nejake dalsie veci a uvedomil som si, ze aktualne to sme schopni urobil len my, HTML-compatible writeri. Takze by bolo dobre vyrobit `_data/carousel-successes.yml`, ktory bude mat info o jednotlivych slidoch. Od oka asi titulok, popis, link, filename obrazku a nejaky priznak displayed true/false (mozno este nejaky sposob ovplyvnovania poradia?).

Takuto konfiguraciu uz zvladnu editovat v projekte viaceri, nebdue to visiet na nas.

Este k tej poznamke kontrole rozlisenia: Je zasadne, aby obrazok bol v spravnom rozliseni/pomere stran, lebo inak ten carousel nevyzera dobre (automaticky fit je pomerne narocna vec, aby fungoval vsade a dobre). Takze optional bonus je zaradit do build procesu nieco, co skontroluje, ze carousel obrazky maju spravne rozlisenie (nizka priorita a netusim, ako na to).

Mrknes sa teda na tu technicku cast niekedy v blizkych dnoch?

**Comment by mukrop** [comment]
Knock, knock, pripominam sa, ci si sa k tomuto dostal :-).
