### ISSUE TITLE
Grafika: mapa zemí plnících závazky Pařížské dohody

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web-cz#735]
návrh na novou infografiku - poslouchám ten podcast (čtená kniha Neobyvatelná planeta) co tu někdo doporučoval onehdá, a přišlo mi zajímavé, jak tam říká a vyjmenovává země, které plní Pařížskou dohodu, je jich asi 5 či kolik. Bylo by fajné na to mít údernou infografiku - co myslíte? Ukázka zde 
![image](https://user-images.githubusercontent.com/5269350/104809191-af01e480-57eb-11eb-8539-01cade336833.png)

**Comment by ondraspribyla** [comment]
Spíš by dávalo smysl nějak zobrazit země, které se přihlásily k net-zero nebo které mají snižování emisí ve své legislativě... Tento visící nápad zavírám, časem to může být třeba explainer...
