### ISSUE TITLE
Updatovat grafiku a data teplotní anomálie o rok 2020

### ISSUE THREAD

**Issue by katkolouchova** [faktaoklimatu/web-cz#739]
+ je potřeba ještě upravit v grafice počet stanic na 20 000

https://data.giss.nasa.gov/gistemp/tabledata_v4/GLB.Ts+dSST.txt

**Comment by katkolouchova** [comment]
@jankrcal Jeňo, mohl bys prosím aktualizovat dataset, nebo mi dát práva k jeho úpravě?

**Comment by jankrcal** [comment]
Katko, dal jsem Ti přístup. Postup:
 - pokud je to triviální úprava, tak to prosím udělej přímo v tom souboru
 - pokud je to větší úprava, tak prosím udělej kopii na sdílený disk, tam to uprav a v PR změň odkaz na tento upravený dokument (a já to přesunu na disk datasetů).

**Comment by katkolouchova** [comment]
@jankrcal Děkuju, udělala jsem si kopii. Všimla jsem si, že se někde o 1 nebo 2 setiny změnila data v minulosti oproti tomu, co máme v datasetu. Jak to budeme řešit? Necháme data, jak jsou (změna není zásadní) s nějakým disclaimerem, nebo překreslíme graf?

Změna se týká i [anomálie za 22 000 let](https://faktaoklimatu.cz/infografiky/teplota-22000-let). Můžeš mi prosím dát přístup i k tomuto datasetu? 

Navíc jsem si všimla, že dataset u [anomálie od roku 1880](https://faktaoklimatu.cz/infografiky/teplotni-anomalie) odkazuje rovnou na dataset k anomálii za 22 000 let. Přemýšlím, jestli to tak nenechat (i když je pak potřeba delší čas na orientaci, pokud hledám data jenom od roku 1880), abychom nemuseli každý rok upravovat oba soubory.

**Comment by katkolouchova** [comment]
K té aktualizaci dat -- včera jsme se s Ondrášem domluvili, že dataset budeme držet stejný jako v NASA. Navíc grafu se změny v podstatě nedotknou, jelikož se jedná o setiny.
Takže už mám jenom otázku, na který dataset odkazovat.

**Comment by jankrcal** [comment]
Mrzí mě, že nereaguju, měl jsem velmi intenzivní pracovní týden, tak jsem fakta trochu pouštěl.

Jsem pro držet jen jeden dataset pro obě grafiky. Nastavil jsem Ti editorská práva k tomu datasetu
https://docs.google.com/spreadsheets/d/1XDa9X1W-bEJhKYMtefvwPuz5N0l2HPyio5dR5KI9qsY/edit#gid=979818322

Pokud jsem Ti neodpověděl na poslední otázku, tak to znamená, že jsem ji nepochopil. Pokud tak, můžeš jí prosím nějak přeformulovat?

**Comment by katkolouchova** [comment]
Nic se neděje, všechny informace viz PR :)
