### ISSUE TITLE
Bug: rozbitý rozbalovací menu na stránkách Atlasu

### ISSUE THREAD

**Issue by setcz** [faktaoklimatu/web-cz#741]
https://faktaoklimatu.cz/atlas - text je o řádek pod šipečkou:
<img width="549" alt="Screenshot 2021-01-18 at 20 41 19" src="https://user-images.githubusercontent.com/10813593/104957051-b08b0280-59cd-11eb-8380-537bb4af47bb.png">

A po kliknutí na jeden ten rozbalovací řádek se objeví divnej modrej obdélník:
<img width="1155" alt="Screenshot 2021-01-18 at 20 41 30" src="https://user-images.githubusercontent.com/10813593/104957108-ce586780-59cd-11eb-915a-48cd981af56e.png">
<img width="1205" alt="Screenshot 2021-01-18 at 20 41 44" src="https://user-images.githubusercontent.com/10813593/104957115-d31d1b80-59cd-11eb-9a1f-781fd470e2a6.png">

(Chrome, MacOS)

**Comment by mukrop** [comment]
To bude pozostatok redesignu textov, na stranku atlasu sa zabudlo. Mrknete na to @jankrcal alebo @mgrabovsky ?

**Comment by jankrcal** [comment]
Nechal bych tam rozbalovací prvky, nejsem si jistý, že chci aplikovat redesign včetně TOC i zde. A tak jako tak mi přijde užitečný opravit kód rozbalovacích boxíků (teda pokud ho nechceme z webu úplně smazat).
