### ISSUE TITLE
Přidat úspěchy do carouselu na titulní stránku

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-cz#748]
* Doplnit obrazok pre atlas.
* Doplnit obrazok a text pre Cenu za komunikaci klimaticke zmeny.

**Comment by jankrcal** [comment]
A co výhra v Climate Challenge? Sice to máme v patičce, ale tam by ten text šel zkrátit.

**Comment by jankrcal** [comment]
Carousel už na titulce není.
