### ISSUE TITLE
local build AKTUALITY hyperlinky neklikatelné

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web-cz#751]
zde http://localhost:4000/aktuality

mi nejde klikat na většinu hyperlinků, namátkou např hned nahoře 
![image](https://user-images.githubusercontent.com/5269350/105641300-79ac6500-5e83-11eb-860b-d960929f8eae.png)

oproti tomu na hyperlink tento 
![image](https://user-images.githubusercontent.com/5269350/105641311-88931780-5e83-11eb-85f0-ee2ac52f124f.png) kliknout de.

Vyzkoušeno jak v Brave, tak v Chromium.
(Ani ve Firefoxu to nejede)

Nevím, kde je chyba, nezkoumal jsme, jen reportuju...

**Comment by mukrop** [comment]
To rozbili zmeny od @jankrcal  v 142d3529 (zaporny margin-top a height kvoli TOC).

**Comment by mukrop** [comment]
A @crysman, skus prosim rovno priradovat k issues aj stitky a projekt :-).

**Comment by mukrop** [comment]
Prosim @jankrcal o opravu, pozna si svoj kod najlepsie. (Ak to neurobi rychlejsie @mgrabovsky.)

**Comment by jankrcal** [comment]
To je součást Matějovy opravy skrolování na daný odkaz, už jsme na to naráželi u rozbalovacích boxíků.

Matěji máš kapacitu se podívat na nějaké koncepčnější řešení? (já bych to klidně omezil na h2 a h3 uvnitř .longread, tedy jenom na nadpisy, ke kterým vedou linky z TOC).

**Comment by mgrabovsky** [comment]
Podívám se na to zítra večer.

**Comment by jankrcal** [comment]
Díky!

Dne ne 24. 1. 2021 21:03 uživatel Matěj G. <notifications@github.com>
napsal:
