### ISSUE TITLE
Grafika emisí z fosilních paliv a výroby cementu

### ISSUE THREAD

**Issue by katkolouchova** [faktaoklimatu/web-cz#762]
Nová grafika podle dat Global Carbon Budget.

**Comment by ondraspribyla** [comment]
Poznámky: 
- člověk má dojem, že emise neklesají vůbec, ale ony klesají v určitých regionech. 
- vysvětlit rozdílné použití a charakteristiky: auto na uhlí nejezdí + emise z těžby + emisní intenzita při výrobě elektřiny 
- sektor využití: výroba elektřiny, doprava, spalování v průmyslu, ...
- ad cement - vysvětlit, zda jde o emise z reakce nebo i ze spalování
-
