### ISSUE TITLE
Aktualizovat grafiku potenciál opatření

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-cz#764]
Měli bychom aktualizovat grafiku potenciálu opatření a dát tam čísla konzistentní s grafikama scénářů:
https://faktaoklimatu.cz/infografiky/potencial-zpusobu-snizeni-emisi

Úkoly:
 - drobná aktualizace textu (naznačit metodiku počítání emisí, text vzít z textů scénářů),
 - drobná aktualizace datasetu,
 - drobná aktualizace grafiky.

**Comment by jankrcal** [comment]
Návrh úpravy pro scénáře: 

Varianta 1: Scénář NECP
Varianta 2: Scénář Energynautics
Varianta 3: Scénář BloombergNEF
Varianta 4: Scénář Ember

Hodnoty emisních úspor a v procentech jsou v této tabulce:
https://docs.google.com/spreadsheets/d/1Mfua6djrufHgLh2MjNLxkJd7NxtaK1vVX2m8xLPGZLg/edit#gid=1417764945

**Comment by ondraspribyla** [comment]
Skvělý :-) ať nám to tu dlouho nevisíí :-)

**Comment by jankrcal** [comment]
Kristi už mi dodala grafiku, teď je to na mě (někdy příští týden)

**Comment by jankrcal** [comment]
Kromě toho jsem se koukal na teplo v domácnostech:

Dostal jsem relevantní připomínku, že tam nezapočítáváme emise z tepla dodaného z tepláren. To mi skutečně přijde zavádějící a tak jsem se ponořil hlouběji do dat a vyhrabal čísla ze zprávy ERÚ (o teple)[1] a emisní faktory z českého National Greenhouse Gas Inventory Reportu [2].

Vyšlo mi tam dalších 3.3 Mt CO2 (oproti 9.1 Mt z toho, co se spálí přímo v domácnostech), což mi high-level dává smysl, tak bych to zveřejnil. Na grafice by se to projevilo jako úspora 6.2 Mt (4.2 %) místo současných 4.6 Mt (3.5 %)

Celkově je tam několik zjednodušení:
 - ERÚ udává zdroje na výrobu dodaného tepla a podíl sektorů na dodaném teple (domácnosti asi 40 %). Z toho nejde usoudit, které zdroje na výrobu tepla byly použity přímo pro domácnosti. Beru produkt těchto dvou faktorů, tedy předpokládám uniformní rozložení.
 - Opět uniformě rozpočítávám teplo, které padne na vlastní technologickou spotřebu a na ztráty při distribuci (prostě, aby domácnosti nesly úměrný podíl na těchto ztrátách).
 - Emisní faktory beru trochu uvolněně: pro ostatní pevná paliva beru faktor pro dehet, pro ostatní plyny beru koksárenský plyn, na celkové emise by to nemělo mít zásadní efekt.

Tabulka je zde: https://docs.google.com/spreadsheets/d/1Mfua6djrufHgLh2MjNLxkJd7NxtaK1vVX2m8xLPGZLg/edit#gid=1441103813
**Oldo, myslíš, že by ses to po mě mohl v rychlosti zkontrolovat?**

[1] http://www.eru.cz/documents/10540/5391330/Zprava_o_provozu_TS_2018.pdf/bec4c828-cc45-4c94-89dd-f156bf49165c
[2] https://unfccc.int/sites/default/files/resource/cze-2020-nir-7may20.pdf

**Comment by SklenarOldrich** [comment]
V návaznosti na náš telefonát tímto potvrzuji správnost Jeňova výpočtu :)

**Comment by kikinna** [comment]
@jankrcal Znamená to, že mám zanést změnu pro domácnosti?

**Comment by jankrcal** [comment]
Ano, prosím!

(děkuju, že se ptáš, prostě jsem se jen nedostal k tomu, tě poprosit)

Dne čt 1. 4. 2021 10:00 uživatel kikinna ***@***.***> napsal:

**Comment by kikinna** [comment]
Jéni, je to [tady ](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/policies/czechia/emission-decrease-potential-in-czechia/cs-potencial-zpusobu-snizeni-emisi.pdf) vyexportované. Prosím udělej rychlej check, že jsou hodnoty ok.
