### ISSUE TITLE
UK mimo EÚ -> úprava infografík?

### ISSUE THREAD

**Issue by LenkaSedlackova** [faktaoklimatu/web-cz#767]
Ahoj,

teraz mi napadlo pri príprave SK verzie FoK, či by výhľadovo nebolo vhodné upraviť infografiky (emisné) up-to-date = Británia už nie je členom EÚ. Neviem, či niekto chystá upravovať aj dáta, aby boli čo najviac aktualizované, ale ak hej, tak by sa mohlo myslieť aj na to.

**Comment by ondraspribyla** [comment]
1. EU používáme hlavně proto, že jde o určitý logický celek... myslím, že to budeme řešit  přeznačením na EU28 nebo EU + GB
2. Znamenalo by to zpětně řešit konzistenci značení dat a buď bychom museli vyjmout GB zpětně ve starších údajích, nebo tam zobrazovat skok, který pak budeme vysvětlovat. Nejde jen o grafy o emisích, ale třeba i údaje o výrobě elektřiny od roku 1990...
Myslím, že to vyvstane přirozeně při aktualizaci dat znovu jako otázka, ale jako issue bych si to nedržel. Jako issue to tedy zavírám.
