### ISSUE TITLE
Odkazy na Náš dataset u vícero infografik jsou rozbité

### ISSUE THREAD

**Issue by jandolezal** [faktaoklimatu/web-cz#772]
U některých infografik v sekci Podkladová data je odkaz Náš dataset nefunkční. Týká se to například infografiky [Největší emitenti v ČR](https://faktaoklimatu.cz/infografiky/nejvetsi-emitenti-cr), kde je uveden nefukční odkaz [Náš dataset](https://emise-cr/). 

Zdá se, že se to týká více infografik, např. [Pořadí států EU podle emisí skleníkových plynů](https://faktaoklimatu.cz/infografiky/emise-eu-poradi). Nezkoumal jsem detailně, ale asi mají společné, že jde o tlačítko Náš dataset.

**Comment by ondraspribyla** [comment]
Díky za upozornění!
O.

**Comment by mukrop** [comment]
Opravene, dakujeme za nahlasenie :-).
