### ISSUE TITLE
Upravit cover obrázky explainerů, aby dodržovaly licenci

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-cz#778]
[Obrazok](https://commons.wikimedia.org/wiki/File:Factory_of_National_Cement_Share_Company.jpg), ktory pouzivame na epxlainer o cemente je CC, tj. potrebuje mat uvedeneho autora a licenciu (a idealne skratka licencie odkazuje na plne znenie na stranky CC).

Kazdopadne aktualne je tam len link na "zdroj obrazku", prosim o poctivejsie spracovanie.
Jedna moznost je vacsi text, ale asi by som isiel do nejakeho riesenia cez hover, alebo rozklik (kvoli mobilom je rozklik asi lepsi).

**Comment by jankrcal** [comment]
Ano, počítám s tím.
