### ISSUE TITLE
Aktualizovat dataset co-2 o data za rok 2020

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-cz#784]
Dataset [1] obsahuje několik listů k aktualizaci:
 - SCRIPPS už zveřejnil 'merged ice-core & averaged products' do 2020 včetně [2],
 - MLO CO2 měsíční data (Keeling) už jsou taky do konce roku ([3], momentálně ftp rozbité)
 - MLO O2 měsíční data taky jde protáhnout o cca 8 měření [4]

Grafiky není třeba moc aktualizovat, protože to nepůjde vidět. Maximálně tak upravit tyrkysové číslo na https://faktaoklimatu.cz/infografiky/koncentrace-co2 na '412 ppm' jako nice-to-have.

Možná využít tuto příležitost a konečně rozmyslet #770.

[1] https://docs.google.com/spreadsheets/d/1DYrIsmgy_S6IIWGtsk55Jor6zSDrf6-qT8Og9n7oDoU/edit#gid=979818322
[2] https://scrippsco2.ucsd.edu/assets/data/atmospheric/merged_ice_core_mlo_spo/merged_ice_core_yearly.csv
[3] ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_mm_mlo.txt
[4] https://scrippso2.ucsd.edu/assets/data/o2_data/o2_monthly/mloo.txt

**Comment by LenkaSedlackova** [comment]
ahoj, 
keď už spomínaš tú IG, tiež maximum CO2 [ppm] sa zmenilo - minulý mesiac bolo 419 ppm (v SK verzii IG už to je aktualizované)

**Comment by ondraspribyla** [comment]
Odkud bereš to maximum 419ppm? viz https://www.co2.earth/ nebo
https://scrippsco2.ucsd.edu/data/atmospheric_co2/primary_mlo_co2_record.html
ukazují maximum 417ppm z loňského května...

tyhle úpravy dat prosím diskutuj s Jeňou nebo s Ondrášem (viz oznámení ve
slacku)

**Comment by LenkaSedlackova** [comment]
je to daily CO2 baseline value z 4.2.2021, zdroj https://scrippsco2.ucsd.edu/data/atmospheric_co2/mlo.html - in situ CO2 daily dataset

**Comment by ondraspribyla** [comment]
K něčemu je to dobrý :-) zjistil jsem, že skutečně cca kolem 7 února byl
výkyv v měřené koncentraci - viz tweet
https://twitter.com/CO2_earth/status/1366420938040958979

Právě kvůli takovým výkyvům používáme měsíční data a ne denní data...
Podrobněji k používaným datům zde:
https://docs.google.com/spreadsheets/d/1DYrIsmgy_S6IIWGtsk55Jor6zSDrf6-qT8Og9n7oDoU/edit#gid=979818322

O.

**Comment by jankrcal** [comment]
Hotovo
