### ISSUE TITLE
Přidat do emisního koláče info a LULUCF

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-cz#803]
Kvůli kůrovci (a místní reakci na něj) se emise v sektoru LULUCF mění ze záporných na kladné:
 - v roce 2016 to bylo -5.3 MtCO2eq
 - v roce 2018 uz +5.8 MtCO2eq
 - v roce 2019 by to melo byt (podle predbeznych dat, [1]) +13.3 MtCO2eq!

Chtel bych dostat nejake zakladni info (hvezdicku) do grafik:
  * https://faktaoklimatu.cz/infografiky/emise-cr-detail
  * https://faktaoklimatu.cz/infografiky/emise-cr

Navrhuju dat hvezdicku primo za podnadpis: "Celkove emise CR 2018 *"
A hvezdicka by pak rikala:

[hlavní verze]
Pro srovnávání emisí napříč státy EU vynecháváme kategorii "Využívání krajiny, změny ve využívání krajiny a lesnictví". Díky ukládání uhlíku v zeleni má totiž tato kategorie ve většině států EU záporné emise, což komplikuje vizualizaci. **V Česku jsou ovšem v posledních několika letech kladné** kvůli výrazné těžbě dřeva při kůrovcové kalamitě. **Za rok 2018 to bylo 5,8 Mt CO2eq navíc k údajům výše.**

[alternativa 1]
Pro možnost vizuálně srovnávat emise napříč státy EU nezobrazujeme kategorii "Využívání krajiny, změny ve využívání krajiny a lesnictví". Ta je totiž ve většině států EU celkově záporná, protože zeleň zachytává uhlík. V Česku jsou v posledních několika letech kladné kvůli výrazné těžbě dřeva při kůrovcové kalamitě. **Za rok 2018 to bylo 5,8 Mt CO2eq navíc k údajům výše.**

[alternativa 2]
Z prezentačních důvodů nezobrazujeme emise z "Využívání krajiny, změny ve využívání krajiny a lesnictví", které jsou ve většině států EU v součtu záporné (zeleň zachytává uhlík). V Česku jsou v posledních několika letech kladné kvůli výrazné těžbě dřeva při kůrovcové kalamitě. **Za rok 2018 to bylo 5,8 Mt CO2eq navíc k údajům výše.**

[1] https://www.eea.europa.eu/data-and-maps/data/approximated-estimates-for-greenhouse-gas-emissions-2

**Comment by jankrcal** [comment]
@ondraspribyla @kikinna Připravil jsem nástřel textu k hvězdičce k emisnímu koláči (LULUCF). Prosím o komentáře.

**Comment by ondraspribyla** [comment]
Souhlas. Zkoušel jsem chvíli vymyslet jinou formulaci než "z prezentačních
důvodů" ale na nic lepšího jsem nepřišel...

O.

**Comment by jankrcal** [comment]
Ještě mě napadá alternativní trochu delší a konkrétnější důvod "Pro možnost vizuálně srovnávat mezi státy EU nezobrazujeme emise ..."

Zatím ještě trochu kostrbatý a vlastně mi to přijde spíš slabší.

**Comment by ondraspribyla** [comment]
Tahle nová formulace mi přijde ještě lepší

Dne so 20. 3. 2021 15:53 uživatel jankrcal ***@***.***>
napsal:

**Comment by jankrcal** [comment]
Přeformuloval jsem, prosím Kristi o komentář, až se vrátí s dovolené.

**Comment by kikinna** [comment]
Děkuji moc za práci a popisky jsou pěkné. Ale.  Opravdu po mě chcete, abych do grafiky, která nemá už téměř žádné místo dala popisek, který bude odhaduji cca dvakrát tak dlouhej jako vysvětlení CO2eq? Já na to fakt nemám místo a míra detailu, která je v popisku mi nesedí k úrovni detailu, která je ve zbytku grafiky.

Zároveň mi není jasné, proč to nezobrazíme v koláči ČR - je to jen ČR, tady zrovna to nesrovnáváme s žádnými jinými státy, tak je třeba se toho držet? Obzvlášť pokud v roce 2018 jsou emise už nezáporné? 
Možná je to na rychlý call a rychlé doplnění informací.

**Comment by ondraspribyla** [comment]
...nevím jak to řešit. Podle mě teď trochu řešíme 
1. preventivní obranu, aby nám nikdo nenadával, že nezobrazujeme LUCULUF
2. reálný problém, kdy emise z LUCULUF pro česko začínají být kladné

Možná není vhodné tlačit to do stávající grafiky, nebo fakt jen jako poznámku typu "Emise z lesnictví a využití půdy nezobrazujeme, více v doprovodném textu." ??

Obecně: Defenzivu bych řešil v doprovodném textu, problém se kladnými emisemi LUCULUF kvůli kolapsu českých lesů dedikovanou grafikou... Co myslíte?

**Comment by jankrcal** [comment]
Chtěl bych aspoň minimalistickou poznámku i v grafice, protože je naše (asi) nejpoužívanější grafika a v tomto směru může být zavádějící.

Ondrášova jedna věta mi přijde použitelná, jen bych prohodil slovosled:
"Nezobrazujeme emise z lesnictví a využití půdy, více v doprovodném textu."

**Comment by kikinna** [comment]
Ok, takovou poznámku tam můžu dostat. 
Nicméně ještě se pro jistotu zeptám - nestálo by za to je tam prostě přidat do toho koláče za rok 2018? Nebo jaký důvod přemýšlím, že tam chceme dávat poznámku "něco neuvádíme" místo toho, abychom to přidali do samotné vizualizace?

**Comment by ondraspribyla** [comment]
... emise z lesnictví jsou po většinu času záporné. Záporné emise v koláči
nezobrazíš. To, že jsou teď kladné je změna, sice významná, ale bude se
ještě upravovat, podle toho, jak se budou upravovat "guidelines" pro
účetnictví...

**Comment by kikinna** [comment]
Ok, hodím zatím jen poznámku. Někdy se ráda dozvím víc info )

**Comment by jankrcal** [comment]
@kikinna Máš to upraveno, že bych k tomu udělal PR a napsal text?

**Comment by ondraspribyla** [comment]
@jankrcal Tohle vidím na webu vyřešeno - zavírám...
