### ISSUE TITLE
Bug: nerozbaluje se tlačítko

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#811]
Repoertuju bug: na stránce datasetu https://faktaoklimatu.cz/datasety/koncentrace-co2 se nerozbaluje tlačítko s původními zdroji dat - tedy nelze se znadno doklikat k původním datům.

Budu rád, když na to @mukrop nebo @mgrabovsky  případně @Tasssadar mrkne...

**Comment by mgrabovsky** [comment]
Vypadá to, že rozbalovací tlačítka nefungují nikde. V konzoli se vypisuje chyba `Uncaught TypeError: a.default is not a constructor`. Možná to souvisí s nedávným [updatem na nové verze knihoven](https://github.com/faktaoklimatu/web-core/pull/50)? Bohužel teď nemám prostor to prozkoumat.

**Comment by mukrop** [comment]
Yop, je to clash verzii Bootstrap a Popper.
