### ISSUE TITLE
Aktualizovat a doplnit energetické scénáře

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-cz#829]
Má to dvě části:
 - aktualizovat scénář Bloomberg pro variantu 55% (na které se v mezičase Evropa dohodla)
 - přidat scénář McKinsey

Data k obojímu už +- je v tabulce https://docs.google.com/spreadsheets/d/14CB428mF-_iHTgrLb2Dd0zJZ4xHUMdGhbr_FZ2fZy6k/edit#gid=1202912332

TODO ke grafice:
 - [Kuba] vyjasnit si detaily s autory studie McKinsey [Kuba]
 - [Jeňa] napsat úpravy textu do grafiky Bloomberg
 - [Kuba?] napsat text do grafiky McKinsey (včetně drobných textů do srovnávací grafiky https://faktaoklimatu.cz/infografiky/srovnani-energetickych-scenaru-cr)
 - [Kristi/Káťa?] Udělat úpravu grafik a jednu novou grafiku

TODO pro PR:
 - [Jeňa] napsat úpravy doprovodného textu Bloomberg (nějak tam vysvětlit, že jsme dřív měli jiná čísla a jinou verzi, možná na to mít i nějak formátovaný box, podobná pozn. se objevila v textu vybraná opatření, tak takový box tam taky použít)
 - [Jeňa] napsat drobné úpravy doprovodného textu do srovnávací grafiky (opět možná diff box), příp. do rešerše
 - [Kuba?] napsat doprovodný text McKinsey

**Comment by jankrcal** [comment]
Kubo, prosím o zprávu, až budeš mít dost info od McKinsey!

**Comment by katkolouchova** [comment]
Klidně si úpravu a tvorbu grafiky vezmu na starost. Stačí, když mi dáte vědět, až budou data ve finálním stavu :)

**Comment by jankrcal** [comment]
Pracovní návrh na úpravu textu do grafiky BloombergNEF:

Na konec prvního odstavce přidat:
Tato studie předpokládá cíl 55% snížení emisí v EU a očekává značný růst cen emisních povolenek. Jde o rozšíření dřívější studie, která pracovala s původním 40% cílem.

Třetí odstavec:
Hlavní závěr modelu je, že do roku 2027 vytlačí čistě ekonomické tlaky všechny české uhelné elektrárny z trhu. To bude způsobeno z jedné strany růstem cen emisních povolenek, z druhé strany pak dalším poklesem investičních nákladů obnovitelných zdrojů.

INVESTICE
12 mld € na výstavbu nových obnovitelných zdrojů energie (a 2 mld € na výstavbu nových plynových zdrojů). Investice do infrastruktury ani investice do střešní fotovoltaiky studie nemodeluje.

**Comment by jankrcal** [comment]
Když se to ukáže moc dlouhý, můžu zkrátit.

**Comment by jakub-zamouril** [comment]
Text a data pro novou infografiku McKinsey (text pod infografiku je ještě rozpracovaný):
Text: https://docs.google.com/document/d/1rLoPJOsxS4ScUKyF1m2hmlFFUynK2ySXdLtU_qIeCGA/edit?usp=sharing
Data: https://docs.google.com/spreadsheets/d/14CB428mF-_iHTgrLb2Dd0zJZ4xHUMdGhbr_FZ2fZy6k/edit?usp=sharing

Kristi psala, že má hodně práce, měla bys na to teda čas ty, Katko? @katkolouchova

**Comment by katkolouchova** [comment]
Ano, dostanu se k tomu snad během týdne :)

**Comment by jakub-zamouril** [comment]
@katkolouchova Mohla bys Káťo nejdřív aktualizovat tu srovnávací infografiku? Tu budu ukazovat na mojí přednášce. Tady jsou všechny potřebné informace:
https://docs.google.com/document/d/1041XdTl8F2gDWAgFQ_UQDvpGY1n2KgYxlJoEIZiF524/edit?usp=sharing

**Comment by jakub-zamouril** [comment]
Jeňa objevil chybu ve výpočtu emisí u studií Ember a energynautics. Tím pádem bude potřeba aktualizovat i jejich infografiky a opravit tam údaj o emisích.

Ember: https://faktaoklimatu.cz/studie/2020-scenar-ember
Místo 9,3 by emise měly být 9,6

Energynautics: https://faktaoklimatu.cz/studie/2018-scenar-energynautics
Místo 20,9 by emise měly být 22,5

**Comment by katkolouchova** [comment]
@jakub-zamouril Jojo, Kubo, upravím tedy nejdřív tu. Akorát se k tomu asi dostanu až v neděli nebo začátkem týdne.

**Comment by jakub-zamouril** [comment]
> 
> 
> Text a data pro novou infografiku McKinsey (text pod infografiku je ještě rozpracovaný):
> Text: https://docs.google.com/document/d/1rLoPJOsxS4ScUKyF1m2hmlFFUynK2ySXdLtU_qIeCGA/edit?usp=sharing
> Data: https://docs.google.com/spreadsheets/d/14CB428mF-_iHTgrLb2Dd0zJZ4xHUMdGhbr_FZ2fZy6k/edit?usp=sharing
> 

Text pro McKinsey je hotový

**Comment by jakub-zamouril** [comment]
Sepsal jsem úpravy pro text pod srovnávací infografikou:
https://docs.google.com/document/d/12ZQqAtwQQCct9ALS9lXOOWGEQNxIrFqRf0_h4x-gqAg/edit?usp=sharing

Pro aktualizaci srovnávací infografiky a vytvoření McKinsey by tak mělo být vše připravené.

**Comment by katkolouchova** [comment]
> 
> 
> Když se to ukáže moc dlouhý, můžu zkrátit.

@jankrcal Jeňo, tak tak se to tam vejde, ale jednotlivé sekce jsou moc namačkané. Mohl bys prosím v některé části ubrat cca 10 slov? :) Teď to pro představu vypadá takto:
![image](https://user-images.githubusercontent.com/49321752/120846512-8304b700-c572-11eb-968d-381359b4eaab.png)

**Comment by jankrcal** [comment]
Tak navrhuju smazat poslední větu sekce O SCÉNÁŘI (ono je to stejný stejně o odstavec výše, toho jsem si nevšiml).

A dále zkrátit INVESTICE následovně:

14 mld € na výstavbu nových zdrojů elektřiny. Investice do infra...

**Comment by jankrcal** [comment]
Kdyby snad nestačilo, napiš!

**Comment by katkolouchova** [comment]
Už se to tam krásně vejde, díky! Všimla jsem si, že u Bloombergu se některé hodnoty změnily opravdu hodně, třeba větrný potenciál mají dokonce vyšší, než je optimistická varianta ze studie Ústavu fyziky atmosféry, ze které zpracováváme větrný potenciál pro ČR. Zároveň mě překvapil skok v koeficientu využití biomasy.

@jankrcal @jakub-zamouril Prosím, koukněte na to, jak jsem vyřešila to, že v McKinsey zahrnují bioplyn do plynu a ne do naší kategorie biomasa, bioplyn. Mazat bioplyn z naší kategorie jsem nechtěla, protože z toho vychází ERÚ a stav v roce 2019, ale je to trochu matoucí, že pak škrtám čtvereček v instalovaném výkonu. Ale přijde mi to jako nejlepší řešení v rámci zachování konzistence. Co myslíte?

Tuto poznámku jsem vložila i do srovnávací grafiky, kam jsem zároveň přidala vysvětlení, co je NECP. Přišlo mi, že to pak bude srozumitelnější. Od Kuby zazněl návrh seřadit scénáře v této grafice podle velikosti emisí od nejvyšších, aby vizuálně lépe navazovaly na rok 2019. Po delším přemýšlení bych ale za mě preferovala ponechat seřazení od nejnižších – přijde mi, že tím, že tyto scénáře budou výš, na ně upíráme větší pozornost a na první pohled říkáme ano, je možné být ambiciózní a emise takto snížit. Zatímco když jsou dole, působí na mě víc naivně. Snad chápete, co myslím. Pokud to vidíte silně jinak, dejte vědět.

![cs-scenare-transformace_cs-2021-scenar-mckinsey](https://user-images.githubusercontent.com/49321752/120893068-7b481f80-c611-11eb-87f3-d20b5dec5f0c.png)

![cs-srovnani-energetickych-scenaru-cr](https://user-images.githubusercontent.com/49321752/120893077-8602b480-c611-11eb-87f1-d2a59f9d4ce0.png)

**Comment by jankrcal** [comment]
Hlasoval bych pro zjednodušení u McKinsey: Vzhledem k tomu, že říkali, že ten bioplyn není velký, tak bych prostě vzal současné hodnoty pro bioplyn a ty odečetl od plynu a přičetl k biomase:
 - výroba: 2.34 TWh
 - instalovaný výkon: 319.8 MW
Tuto zjednodušení pak musíme okomentovat v doprovodném textu. Co si o tom myslíte? @katkolouchova @jakub-zamouril 


Kuba dále narazil na to, že se nový Bloomberg dost vymyká ve výrobě kategorie Hydro. Tam pro změnu neumíme rozlišit výrobu z přečerpávacích a jiných hydro, tak tam (i u předchozí verze) používáme stejný trik: předpokládáme konstantní výrobu z přečerpávacích (protože nové přečerpávačky nepostavíme). To může být dost nekorektní, protože se jim může zvýšit koeficient využití (vyšší potřeba storage). Tak bych skoro navrhoval místo výroby z pumped hydro fixovat koeficient využití pro  nepřečerpávací hydro a tudíž vzít současnou výrobu z hydra a nafouknout ji úměrně podle zvýšeného instalovaného výkonu. @jakub-zamouril, co myslíš?


To že Bloomberg jde s větrem lehoučce nad potenciál dle studie UFA bych neřešil, jen okomentoval v doprovodném textu.

**Comment by jankrcal** [comment]
Ještě pár komentářů inline:

> Zároveň mě překvapil skok v koeficientu využití biomasy.

Myslíš skok dolů oproti současnosti nebo skok nahoru oproti minulé verzi studie? Oni se v tom původním reportu tváří, že biomasa se dost cenově nevyplatí a tak půjde dolů výroba, ale možná s dražšíma povolenkama se vyplatí víc, tak to zase stouplo. Nevím jistě, protože k té nové verzi nemají v podstatě žádný text.

> Tuto poznámku jsem vložila i do srovnávací grafiky, kam jsem zároveň přidala vysvětlení, co je NECP. Přišlo mi, že to pak bude srozumitelnější. Od Kuby zazněl návrh seřadit scénáře v této grafice podle velikosti emisí od nejvyšších, aby vizuálně lépe navazovaly na rok 2019. Po delším přemýšlení bych ale za mě preferovala ponechat seřazení od nejnižších – přijde mi, že tím, že tyto scénáře budou výš, na ně upíráme větší pozornost a na první pohled říkáme ano, je možné být ambiciózní a emise takto snížit. Zatímco když jsou dole, působí na mě víc naivně. Snad chápete, co myslím. Pokud to vidíte silně jinak, dejte vědět.

Za mě takto dobrý (ostatně to tak bylo), nechal bych. Ale nemám na to silný názor.

**Comment by jakub-zamouril** [comment]
> Hlasoval bych pro zjednodušení u McKinsey: Vzhledem k tomu, že říkali, že ten bioplyn není velký, tak bych prostě vzal současné hodnoty pro bioplyn a ty odečetl od plynu a přičetl k biomase:
> 
>     * výroba: 2.34 TWh
> 
>     * instalovaný výkon: 319.8 MW
>       Tuto zjednodušení pak musíme okomentovat v doprovodném textu. Co si o tom myslíte? @katkolouchova @jakub-zamouril

On v tom scénáři nejspíš bioplyn taky šel dolů, vzhledem k tomu, že biomasa šla dolů, a podle autorů je ho v roce 2030 malé množství. V BloombergNEF, který je taky nákladově optimalizovaný, šly biomasa a bioplyn dolů skoro dvojnásobně. Takže když přičteme současné hodnoty, tak to určitě nadhodnotíme. Já bych se přikláněl k tomu to nechat jak to je teď, Ondráš se k tomu taky tak přiklání.

> Kuba dále narazil na to, že se nový Bloomberg dost vymyká ve výrobě kategorie Hydro. Tam pro změnu neumíme rozlišit výrobu z přečerpávacích a jiných hydro, tak tam (i u předchozí verze) používáme stejný trik: předpokládáme konstantní výrobu z přečerpávacích (protože nové přečerpávačky nepostavíme). To může být dost nekorektní, protože se jim může zvýšit koeficient využití (vyšší potřeba storage). Tak bych skoro navrhoval místo výroby z pumped hydro fixovat koeficient využití pro nepřečerpávací hydro a tudíž vzít současnou výrobu z hydra a nafouknout ji úměrně podle zvýšeného instalovaného výkonu. @jakub-zamouril, co myslíš?


To mi dává smysl. Pravděpodobně to dopadne tak, že u všech scénářů pak bude shodně 2,0 TWh výroba a bude potřeba lehce upravit importy/exporty.

> Tuto poznámku jsem vložila i do srovnávací grafiky, kam jsem zároveň přidala vysvětlení, co je NECP. Přišlo mi, že to pak bude srozumitelnější. Od Kuby zazněl návrh seřadit scénáře v této grafice podle velikosti emisí od nejvyšších, aby vizuálně lépe navazovaly na rok 2019. Po delším přemýšlení bych ale za mě preferovala ponechat seřazení od nejnižších – přijde mi, že tím, že tyto scénáře budou výš, na ně upíráme větší pozornost a na první pohled říkáme ano, je možné být ambiciózní a emise takto snížit. Zatímco když jsou dole, působí na mě víc naivně. Snad chápete, co myslím. Pokud to vidíte silně jinak, dejte vědět.

Jo, tak to nechme jak je to teď

**Comment by jankrcal** [comment]
Teď jsem se o tom bavil s Kubou a pokud se spolehneme na vyjádření člověka z McKinsey, že bioplynu je v roce 2030 málo, tak bych navrhoval následující:
 - nechat data, jak jsou
 - v grafice zrušit hvězdičku
 - okomentovat to v doprovodném textu (že toho bioplynu má být málo, takže ok).

Není mi jasné, jestli si McKinsey myslí, že bude málo i instalovaného výkonu (a bioplynky se budou rušit, tak to teď z té grafiky vypadá) nebo jen málo výroby (a existující bioplynky budou ležet ladem a čekat na lepší časy).

**Comment by jankrcal** [comment]
Upravil jsem Hydro v podkladových datech Bloombergu, výroba trojčlenkou vychází na 2.28 TWh netto.

Import export podle mě upravovat netřeba, prostě jen udáme výrobu bez přečerpávacích a vyjde z toho spotřeba taky bez přečerpávacích. Import zůstane stejný.
