### ISSUE TITLE
Doplnit Velkou Británii do rešerše

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#840]
@Filip-Kessner díky ještě jednou za skvělé zpracování rešerše - zároveň mě napadají věci k vylepšení, tak je budu assgnovat tobě - kdybys tuhle práci nechtěl, tak se prosím ozvi :-)

Přišlo by mi dobré, aby UK byla součástí rešerše - (a možná aby byla zařazena vedle EU?) mimo jiné proto, že ji často dávám za vzor v tom, jak mají zpracovaný závazky a uhlíkový rozpočet. Doplnil bys ji tam prosím? 

Novinka je mimo jiné závazek snížit emise o 78% do 2035
 https://www.gov.uk/government/news/uk-enshrines-new-target-in-law-to-slash-emissions-by-78-by-2035

**Comment by Filip-Kessner** [comment]
UK doplněna ve větvi https://github.com/faktaoklimatu/web-cz/tree/preview-update-reserse-zavazku
