### ISSUE TITLE
Vylepšení rešerše - data aktualizace zemí? 

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#841]
Procházení rešerše a srovnání s nejaktuálnějšími závazku má gap: 

například zpráva z dubna říká, že UK sníží emise o 78% do 2035 https://www.gov.uk/government/news/uk-enshrines-new-target-in-law-to-slash-emissions-by-78-by-2035

ale v databázi NDC https://www4.unfccc.int/sites/NDCStaging/pages/Party.aspx?party=GBR je verze NDC z prosince 2020... 
a CAT bude ještě víc pozadu...

Jinak řečeno, v celé této problematice bude problém s aktualizacema. Přišlo by mi dobré to nějak zohlednit v té rešerši... možná přidáním data aktualizace v tabulce?  Vzhledem k tomu, žes nad tím nejspíš sám přemýšlel teď jen zakládám issue - a můžeme tu prodiskutovat i další myšlenky o vylepšování rešerše.

**Comment by Filip-Kessner** [comment]
Souhlas, s aktuálností dat tady budeme bojovat i v budoucnu. Každý zdroj má nějakou časovou značku a asi by bylo dobré ji uvést. Stejně tak ta rešerše samotná by měla mít datum aktualizace - třeba v intru.

**Comment by Filip-Kessner** [comment]
U "horkých zpráv" mám trochu problém se zdroji. Osobně mám pocit, že CAT, NDC nebo Nature působí věrohodně, ale třeba s tím SkyNews jsem byl na pochybách. Žádné oficiální prohlášení jsem k tomu ale nenašel tak jsem to musel použít. Mám se tím nějak zalamovat? Jsou řekněme "major news outlets" ok?

**Comment by ondraspribyla** [comment]
... nevím. Asi bych byl ochoten brát vážně Reuters, BBC nebo takové... ale
asi bych se tím moc nezalamoval...

**Comment by Filip-Kessner** [comment]
zdroje jsem upravil a doplnil ke všemu datum aktualizace, viz. https://github.com/faktaoklimatu/web-cz/tree/preview-update-reserse-zavazku
Přidáním title parametru (zobrazuje doplněná data aktualizací) do tlačítka jsem ale rozbil jejich řazení. Mohl by se na to podívat @mgrabovsky nebo @mukrop společně s issue 839? Já se v tom moc nevyznám.

**Comment by mukrop** [comment]
Debatu prehadzujem do PR, kde bude vidiet aj relevantne zmeny v kode: https://github.com/faktaoklimatu/web-cz/pull/859
