### ISSUE TITLE
Aktualizovat grafiky co2

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-cz#851]
Založil jsem nový dataset
https://docs.google.com/spreadsheets/d/1v2X6UFA0gUnml7kF0vOByvm4D7R2fFh_mqtnZlOwI0Y/edit#gid=979818322

Moc se toho nezměnilo,
 - CO2 MLO máme do dubna 2021
 - O2 MLO máme do ledna 2021

Podkladový dataset O2 se hodně změnil (mnohem víc datových bodů, jednotlivá měření), objevil se tam jeden zub v roce 2018 (jedno měření je hodně mimo), tak to bude potřeba v grafice asi smazat.

**Comment by mgrabovsky** [comment]
Ve shrnutí se v buňce M24 odkazuje na URL <http://scrippso2.ucsd.edu/assets/data/o2_data/o2_monthly/mloo.txt>, která ale neexistuje. Opravil bych, ale nepodařilo se mi teď narychlo najít, kde ta data jsou.

**Comment by mgrabovsky** [comment]
Nevíš náhodou, Jeňo, proč u O₂ přibyly ty body? Pokud se dobře dívám, ve starém datasetu má každý rok 12 řádků, v novém je to 42.

V každém případě by mi z vizuálního hlediska sedělo, aby ta křivka byla hladká jako teď. Ta nová data jsou dost šumivá a taková úroveň detaily je možná zbytečně rušivá.

**Comment by jankrcal** [comment]
Jo, promiň, ten odkaz jsem zapomněl aktualizovat.

Body přibyly, protože se změnil ten dataset. Ten původní měsíční jsem už bohužel nenašel. Teď máme denní.

Dodělal jsem tam dost pitomě spočítaný průměr po měsících, měl by se tam udělat nějak filtering outliers (minimálně 1ks) a udělat ten průměr váženej podle toho, kde to je v měsící. Později dnes se na to kouknu, teď potřebuju jít ven s dcerou :) Kdybys měl, Matěji, energii něco v mezičase udělat, jsi vítán.

**Comment by jankrcal** [comment]
Tak jsem revertoval změny s O2, protože na vyhlazení a vážený průměr už jsem neměl teď energii. Podle Ondráše není důležité mít O2 super aktuální.

Přidal jsem list, který dělá kombinaci EPICA+Keeling, to by měly být data, se kterýma může přímo pracovat Katka. S tímto je to za mě hotové, na pull request budu mít kapacitu leda až v úterý, tak budu rád, když to někdo jiný aspoň začne třeba v pondělí.

Ondráši, stačí data CO2 do dubna nebo potřebujeme počkat na květnový průměr?

**Comment by jankrcal** [comment]
(dataset https://docs.google.com/spreadsheets/d/1v2X6UFA0gUnml7kF0vOByvm4D7R2fFh_mqtnZlOwI0Y/edit#gid=979818322 jsem už přesunul na cílový disk a nastavil veřejný na čtení, tedy se může dát do pull requestu)
