### ISSUE TITLE
Explainer vlivu CO2 na klima

### ISSUE THREAD

**Issue by jakub-zamouril** [faktaoklimatu/web-cz#854]
Dokončil jsem text explaineru a prokonzultoval s Ondrášem. Zbývá, aby to někdo jiný zkontroloval (třeba jazykově @Jirka-tisnov ?) a pak vysázet a vydat. Tiket zakládám hlavně aby se na to v IPCC-nadšení nezapomnělo. :)
Link na text: https://docs.google.com/document/d/1YFy1DKpLL6du8NwCykAlGHk4rBI1zDAgJu6NNold2ME/edit?usp=sharing

**Comment by jakub-zamouril** [comment]
@Jirka-tisnov Vím že jsi psal že toho máš hodně a že chceš deadliny, ale tohle má nízkou prioritu a nespěchá. Tak zvládl by ses na to podívat do konce června?

**Comment by Jirka-tisnov** [comment]
@jakub-zamouril Kubo, podívám se na to. Pokusím se do konce června. Každopádně na to nezapomenu, přidal jsem si to do seznamu :-)

**Comment by jakub-zamouril** [comment]
Díky Jirko za kontrolu. Mohl bys to File prosím vysázet do Gitu? @Filip-Kessner

**Comment by Filip-Kessner** [comment]
Vysázím, do kdy by to mělo být?

**Comment by ondraspribyla** [comment]
Tvrdý deadline nemáme. Kdyby to bylo možné začátkem července publikovat,
bylo by to super. Text je (narozdíl od toho 1.5°C) finální a pokud by v něm
byly změny, byly by pouze kosmetické. Bude asi potřeba dořešit cover image
(můžeš k tomu něco vybrat? zkoušel bych hledat třeba družice, nebo pohled
na atmosféru z vesmíru, neboť je to docela dost o družicových
měřeních záření v oblasti "Top of Atmosphere"... - ale to je jen moje první
asociace, tebe možná napadnou lepší)
Obrázky v textu jsou od Jakuba dobře odkazované... a bude potřeba doplnit
boxíky a odkazy vpravo od textu - tedy když narazíš na věci, které by měly
být zdůrazněny v bočním boxu, můžeš je tam dát, stejně tak když tě napadnou
prolinky na nějaké naše grafiky či explainery... nebo to pak doplníme do
verze, kterou nahodíš...

Tož tak...

**Comment by Filip-Kessner** [comment]
Za mě by to bylo reálný spíš až poslední týden v červenci. Mám teď tábor, rekonstruujeme a tak.

**Comment by mgrabovsky** [comment]
Rád to vysázím, pokud chcete. Budu teď mít trochu času :)

**Comment by jakub-zamouril** [comment]
Jo, tak to prosím vysázej ty, Matěji, díky :)

**Comment by mgrabovsky** [comment]
Nahodil jsem pull request – #869. Zatím jsem jenom převedl text a ilustrace.

[Preview zde.](https://cz-fakta-o-klimatu--preview-vliv-co2-smhofpfq.web.app/explainery/dukazy-vlivu-co2)
