### ISSUE TITLE
Tlačítko "Explainery" vede na téma emise

### ISSUE THREAD

**Issue by protivinsky** [faktaoklimatu/web-cz#872]
Tlačítko "Explainery" na úvodní stránce přesměrovává na téma emise - https://faktaoklimatu.cz/temata/emise - což nedává smysl. Zároveň nevím, jestli má smysl aby tam to tlačítko vůbec bylo - ideálně bych si všechny explainery našel přes vyhledávání, což teď bohužel taky nejde (zadání vyhledávacího textu "explainer" najde jen grafiky které na nějaký explainer odkazují).

Navrhuji tlačítko opravit nebo úplně vyhodit a následně rozšířit vyhledávání, aby explainery bylo možné najít zadáním klíčového slova explainer.

![image](https://user-images.githubusercontent.com/9573993/121857734-377ea580-ccf6-11eb-80ac-65616967d6e7.png)

**Comment by jankrcal** [comment]
Zmizelo s redesignem webu.
