### ISSUE TITLE
Špatný odkaz v datasetu

### ISSUE THREAD

**Issue by mgrabovsky** [faktaoklimatu/web-cz#881]
V [datasetu k energetickým scénářům](https://docs.google.com/spreadsheets/d/14CB428mF-_iHTgrLb2Dd0zJZ4xHUMdGhbr_FZ2fZy6k/edit#gid=800637961&range=I16) je špatný odkaz na data o instalovaném výkonu (buňka I16) – text je správně, ale odkaz odkazuje na Eurostat.

**Comment by jankrcal** [comment]
Díky, opraveno.
