### ISSUE TITLE
Infografiky pro uhlíkový rozpočet

### ISSUE THREAD

**Issue by jakub-zamouril** [faktaoklimatu/web-cz#883]
Explainer: Uhlíkový rozpočet
https://docs.google.com/document/d/1lNTmf5hGCxUXPABF2K-YgYNoJnw2yp3wTPhg_igx5-A/edit?usp=sharing
- [x] Text
- [ ] Ilustrace
- [ ] Jazyková kontrola

Infografika 1: Závislost oteplení na množství vypuštěných emisí
- [x] Dataset - https://docs.google.com/spreadsheets/d/1J2QcNjXzsRrf8Z8Y3Xh41R_EHlqYKt6CAuN1NUPg2K0
- [ ] Texty - https://docs.google.com/document/d/1CrhaMBB-9djMyZgF_lCun8bkiyIzoBdEalq28B-ZNYQ
- [x] Grafika

Infografika 2: Jak rychle začnem a styl ústupu ovlivní oteplení
- [x] Dataset - https://docs.google.com/spreadsheets/d/1J2QcNjXzsRrf8Z8Y3Xh41R_EHlqYKt6CAuN1NUPg2K0
- [ ] Texty - https://docs.google.com/document/d/1QXi6XIYo51MiAab0YSjO3h7bTTOqHIXMD0Bs1lm67g0
- [ ] Grafika

Infografika 3: Uhlíkový rozpočet svět 
https://github.com/faktaoklimatu/web-cz/issues/337
- [x] Dataset - https://docs.google.com/spreadsheets/d/1ZqHRVRX2Q6Phx5JIQskaYyXqikDXbwL9ZqAYaIh1pbk
- [ ] Texty - https://docs.google.com/document/d/14jZ8C4-bZ_rQnkCkCZrvFLnofryurXK8f5I2cYaX53s
- [ ] Grafika - potřeba aktualizace hodnot

Infografika 4: Uhlíkový rozpočet ČR
- [x] Dataset: https://docs.google.com/spreadsheets/d/15aAAJ8WE95vbYgAXGaJDHiSm1hO9Cq48ycinker4Rvk/edit?usp=sharing
- [ ] Texty - https://docs.google.com/document/d/1IBUYTpOwRUoMhSs8UCyx6-yyWFsLrfxv9LL4AAphwWw
- [ ] Grafika

**Comment by jakub-zamouril** [comment]
@Jirka-tisnov Jirko, mohl bys prosím cca do týdne zkontrolovat text explaineru pro uhlíkový rozpočet? Ten text pak bude rozkopírován pod jednotlivé infografiky podle jejich obsahu, takže se bude na stránkách opakovat víckrát. Pokud bys na to teď neměl čas, dej prosím vědět.
https://docs.google.com/document/d/1lNTmf5hGCxUXPABF2K-YgYNoJnw2yp3wTPhg_igx5-A/edit?usp=sharing

**Comment by ondraspribyla** [comment]
V podstatě hotovo... i když texty a datasety bude potřeba ještě projít a možná trochu vylepšit, protože se dokončovaly narychlo.
