### ISSUE TITLE
video z přednášky Data a souvislosti 23.6.

### ISSUE THREAD

**Issue by anna-macek** [faktaoklimatu/web-cz#890]
@crysman prosím o úpravu videa
https://zoom.us/rec/share/1_pIKKJaBxtwTZRHAmeYi_vrsSyG2WcosmQuMe7yDZCx-21XPo4WeiZ_tR3zeQ8s.XnkMfPIHEAc3P4S0?startTime=1624439163000

**Comment by crysman** [comment]
pořešme ve Slacku, mám nějaké interní věci k tomu a nechci to sem dávat veřejně zbytečně... díky

**Comment by crysman** [comment]
vše se řeší ve slacku, tu zavírám
