### ISSUE TITLE
Špatná sazba matematických rovnic

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#892]
Zjistil jsem, že na stránce https://faktaoklimatu.cz/infografiky/souvislost-koncentrace-oteplovani se špatně zobrazují dolní indexy v rovnici - viz PRTSCR
![Screenshot from 2021-06-29 11-50-19](https://user-images.githubusercontent.com/17317136/123777331-60935e80-d8d0-11eb-9e48-5fe7b2877db4.png)

**Comment by mgrabovsky** [comment]
To možná souvisí s faktaoklimatu/web-core#97.

@mukrop Můžeš prosím updatovat web-core ve web-cz?

**Comment by mukrop** [comment]
Nasadzoval som to zhodou okolnosti dnes.
Je to tam, ale podla mna to problem nevyriesilo.

>

**Comment by mgrabovsky** [comment]
Super, díky. Problém to vyřešilo.

![Screenshot 2021-06-30 at 16-48-33 Souvislost koncentrace CO₂ a globálního oteplování](https://user-images.githubusercontent.com/134321/124000431-d9c7aa00-d9d3-11eb-8176-c3aabb48a365.png)
