### ISSUE TITLE
Překlad grafiky do EN pro Delloite

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#893]
Potřebujeme přeložit https://faktaoklimatu.cz/infografiky/souvislost-koncentrace-oteplovani do 9.července pro Delloite. Zvládnete?

**Comment by Jirka-tisnov** [comment]
Příští týden si plánuju vzít volno (konečně!), nicméně jeden den z toho bude na dohánění restů včetně FoK, takže by se to mělo v pohodě stihnout. Rozpracuju ještě tento týden. 

@katkolouchova Káťo, chceš si zkusit tu vlastní infografiku a na mně nechat text, nebo mám udělat obojí? Jen se ptám, obě varianty za mě OK :-)

**Comment by katkolouchova** [comment]
@Jirka-tisnov Jasně, zkusím a budu pak ráda za proofreading :) Mrknu na to ještě tento týden :)

**Comment by Jirka-tisnov** [comment]
@katkolouchova Deal :-)

**Comment by Jirka-tisnov** [comment]
@mgrabovsky Matěji, potřeboval bych kvůli překladu do AJ přetáhnout do následujícího dokumentu https://docs.google.com/document/d/1EF3Qtldncw7qbrBGGfWu59qwcV89Q7yqpKpZ2zViiLo/edit# první odrážku z https://faktaoklimatu.cz/infografiky/souvislost-koncentrace-oteplovani a pak ještě kus třetí z následující kapitolky ve stejném textu. Jak jsou tam ty rovnice, vždycky se mi to po přetažení rozsype. 

Pomůžeš? Moc děkuji! :-)

**Comment by mgrabovsky** [comment]
Chápu správně, že chceš přetáhnout i ty rovnice? To by mohlo být docela tricky. Pokud je nepotřebuješ, můžeš místo nich napsat jenom nějaký placeholder, třeba `[MATH HERE]`.

**Comment by Jirka-tisnov** [comment]
OK, rovnice vyřeším screenshotem a s tím textem si nějak poradím. I tak ti děkuji! :-)

**Comment by Jirka-tisnov** [comment]
Soubor s překladem zde https://docs.google.com/document/d/1EF3Qtldncw7qbrBGGfWu59qwcV89Q7yqpKpZ2zViiLo/edit# 
Je potřeba @ondraspribyla 
- to pročíst a zkontrolovat
- rozhodnout, co s červenými částmi, jimiž odkazujeme na české texty
- pořešit zobrazování rovnic a proměnných (červeně)

Grafiku ještě potřebujeme doladit s Káťou @katkolouchova (ale už jen drobnosti). Zatím v dokumentu není, jen bokem. 

Dnes cca od 15h jsem k dispozici, v případě potřeby zítra dopoledne :-)

**Comment by katkolouchova** [comment]
@ondraspribyla Přeložená grafika je vložená v dokumentu i ji máš na mailu :)

**Comment by ondraspribyla** [comment]
Ahoj Jiříku

Myslím, že tento překlad je teď Good Enough pro Delloite, tedy poslal jsem
ho Filipovi Hlouškovi a detaily budeme řešit až jej budeme dávat na
anglický web.

O.

**Comment by Jirka-tisnov** [comment]
Dobře, domluveno! :-)

j
