### ISSUE TITLE
Dočištění datasetu "Světový uhlíkový rozpočet"

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-cz#910]
Dnes su zverejnene aktualizovane materialy k uhlikovemu rozpoctu podla AR6. Avsak:
* [Dataset k infografike](https://docs.google.com/spreadsheets/d/1eRY1uSRaUzWk6F1fO4f_7xSbkuhVzJ_lHyXbqGyF9mo/edit#gid=979818322) nie je na spravnom mieste medzi finalnymi datasetmi ale na zdielanom disku v rozpracovanych zlozkach (podobne predosly dataset).
* Kedze data sa tu aktualizovali, chcelo by to na prvom liste datasetu urobit sekciu "Historie změn", ako robime (vid [priklad z emisii](https://docs.google.com/spreadsheets/d/1cHuB4p4Z_vchLbPnnr38rkjDJnlmvjGrvR8A7rrFPTE/edit#g)). Je vlastne nejaky dovod, preco tam ta zelena hlavicka vobec nie je? Nie je to novy standard, ktory by mal byt na vsetkych datasetoch?

Okrem Jeni ako garanta datovych podkladov oznacujem @jakub-zamouril, pretoze podla komentarov odhadujem, ze je autorom datasetu.

**Comment by jankrcal** [comment]
Nedostal se ke mně PR na recenzi. Přesouvání do finálního disku dělám až při PR review.

Hlavičku jsem přehlídnul.

Můžu opravit příští týden, až budu na počítači.

**Comment by jakub-zamouril** [comment]
Já tam ty hlavičky doplním, je to stejné i u ostatních datasetů z kategorie "uhlíkový rozpočet"

**Comment by mukrop** [comment]
V pohode, ja som na to narazil pri mergi updatu AR6, ale boli to veci, co chcel mat Ondras vonku na tiskovku, takze som to hodil von a urobil issue. Nie je to take zasadne, ze by to muselo byt hned, ale v blizkych tyzdnoch by bolo fajn to opravit.

A privadza ma to k myslienke, ze asi potrebujeme PR template, ktory bude mat checklist, pretoze mnoho ludi ani nevie, co vsetko v ramci review treba urobit a niektore chybky robime opakovane.

**Comment by kikinna** [comment]
@ondraspribyla @jankrcal Upravila jsem grafiku podle nového datasetu. 

Mohli byste prosím někdo udělat PR a dostat to na web, ať tam máme co nejdřív správnou variantu? 
[koncept-uhlikovy-rozpocet.pdf](https://github.com/faktaoklimatu/web-cz/files/6967910/koncept-uhlikovy-rozpocet.pdf)

**Comment by jankrcal** [comment]
Já jsem na dovolené bez počítače, z mobilu PR neudělám. Tedy já nejdřív asi
v neděli.

Dne st 11. 8. 2021 13:12 uživatel kikinna ***@***.***> napsal:

**Comment by ondraspribyla** [comment]
Jen dávám vědět, že grafiku uhlíkového rozpočtu jsem opravil a mergnul...

O.

**Comment by jankrcal** [comment]
Ty datasety jsem už uklidil na svoje místo.
