### ISSUE TITLE
chyba v uhlíkovém rozpočtu

### ISSUE THREAD

**Issue by crysman** [faktaoklimatu/web-cz#920]
![image](https://user-images.githubusercontent.com/5269350/133969248-70863119-bb26-47e8-a4ac-a9613402c084.png)

- ta věta jak je teď nedává smysl...

**Comment by crysman** [comment]
resp. možná to smysl dává, ale je to velmi neobratné, musel jsem to číst několikrát, pořád jsem měl dojem, že tam něco chybí. Návrh úpravy: přidat na začátek "koncept" (netučně) - co myslí @Jirka-tisnov  ?

**Comment by crysman** [comment]
představuju si to takto:

> Koncept **Kolik CO<sub>2</sub> lze ještě vypustit**, abychom nepřekročili určitou teplotní hranici, se označuje jako **_uhlíkový rozpočet_**.

**Comment by Jirka-tisnov** [comment]
@crysman To "jako" by tam být mělo, nevím, proč to nakonec vypadlo. Je teda pravda, že tyto grafiky se dokončovaly v dost velkém kalupu. "Koncept" tam dodat lze, ale nevím, jestli se vleze na dva řádky, na což Kristi obvykle tlačí kvůli místu. Nemám ale zásadní problém ani se stávající verzí, mám mlhavý pocit, že to byl nějaký formulační kompromis při boji s místem.

**Comment by crysman** [comment]
to **jako** bych tam chtěl, bez toho to zní fakt divně
já to opravit nemůžu, to je přímo infografika, a já už nemám licenci na Adobe, to jsem měl jen v Rantířově dočasně, takže to musí udělat @faktaoklimatu/designers

**Comment by Jirka-tisnov** [comment]
Ano, to "jako" by tam být mělo. Já měl zato, že jsme ho tam nakonec nechávali. Snad to teda někdo časem opraví, až bude mít chvilku. Myslím, že budem postupně muset víc a víc rozlišovat mezi prioritami a relativními detaily, které jsou "nice to have". Ještě jednou díky za připomínku :-)

**Comment by crysman** [comment]
jasně, rozlišujme/te - přímo tu v GH jsou labels atp. to umíme... nějak jsem to teď olabloval intuitivně
