### ISSUE TITLE
Oprava grafiky Body Zlomu II

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#948]
Ozval se nám Martin Margold z PřF UK s návrhem změny: 
---

ozývám se Vám k infografickému panelu „Body zlomu – kryosféra“, ke kterému bych rád vznesl několik drobných terminologických připomínek. Předně bych chtěl zdůraznit, že panel je vizuálně zdařilý, informativní a dobře vystihuje současné problémy. V použité terminologii se ale nedrží zažitých českých termínů. Česká terminologie do velké míry odpovídá terminologii anglické, která byla použita ve zdrojích, ze kterých jste čerpali.

[Uploading body-zlomu-2_6000_SF.pdf…]()
Nejrozsáhlejší forma zalednění/největší typ ledovce, v angličtině „ice sheet“, je v češtině ledovcový štít nebo kontinentální ledovec. České názvy odpovídají anglickým: Greenland Ice Sheet – Grónský ledovcový štít, West Antarctic Ice Sheet – Západoantarktický ledovcový štít.

Termín „zalednění“ odpovídá anglickému „glaciation“ a značí výskyt ledovců. Mořský led mezi ledovce nepatří a proto v souvislosti s ním slovo zalednění nelze použít.

V příloze posílám panel s vyznačenými navrženými změnami.

Na Přírodovědecké fakultě UK učím předmět „Ice Sheets and Glaciers in the Warming World”
https://is.cuni.cz/studium/predmety/index.php?do=predmet&kod=MZ330P128
který se tématům Vašeho panelu věnuje. Pokud budete mít příležitost, zmiňte se prosím o předmětu těm, pro které by mohl být zajímavý.

 

Děkuji,

S pozdravem,

Martin Margold

**Comment by jankrcal** [comment]
Zkouším nahrát znovu pdf
[body-zlomu-2_6000_SF.pdf](https://github.com/faktaoklimatu/web-cz/files/7513882/body-zlomu-2_6000_SF.pdf)
