### ISSUE TITLE
Úprava grafiky "72% Net zero"

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-cz#952]
Grafika v explaineru, která říká že 72% emisí pochází ze států, které se zavázaly k net zero, už není aktuální. Bude potřeba ji časem nahradit (možná nějakým srovnáním stavu před-po nebo vývojem - to bude nutné promyslet vzhledem k zamýšlenému použití celého explaineru. 

Jako celkem urgentní úpravu bych ale viděl udělat přes grafiku nějaký "razítko" nebo "červený vodotisk" - který naznačí, že tento údaj byl aktuální v řijnu 2021, ale už aktuální není, protože se jednání posunula. (aktuální hodnotu nemusíme zmiňovat - počkáme na konec COPu a analýzy)

@katkolouchova vzala bysis to na starost?

**Comment by katkolouchova** [comment]
@ondraspribyla 
Jojo, dívala jsem na CAT, že tam už Indii mají, ale ještě teda počkejme, až budou konkrétnější čísla a pak zapřemýšlíme, co dál, jak píšeš.

Říkala jsem si, že takto by to mohlo stačit, aby informace byly nadále čitelné a nepůsobilo to přeplácaně. Celý obsah jsem trochu zesvětlila a přidala poznámku pod.
![image](https://user-images.githubusercontent.com/49321752/141680318-5b0d2ffc-5386-42e9-a036-f9b0075f53a8.png)

Jestli se ti to zdá OK, včetně textace, udělám PR.

**Comment by mukrop** [comment]
A chcete to davat do grafiky? (Vizualne mi to tam trochu prekaza.)

Nestacil by vam existujuci warning disclaimer ako [pouzivame v datasetoch](https://faktaoklimatu.cz/datasety/emise-eu)?

![Capture](https://user-images.githubusercontent.com/1871676/141681496-dd6db038-0cbc-4bfe-8ba1-e2cd8ba7dcc4.PNG)

**Comment by katkolouchova** [comment]
Jo, tak to by možná stačilo (jde o grafiku pouze v explaineru) a bude to aspoň konzistentní. Takže hodit tento disclaimer s textem výše nad grafiku by mohlo být dostatečné :) Díky :)

**Comment by katkolouchova** [comment]
@mukrop Napadá mě, jestli podobným způsobem neoznačovat např. i infografiky, pro které už jsou např. data pro další rok(y), ale my jsme je ještě neupdatovali. Založím nové issue.

**Comment by ondraspribyla** [comment]
Souhlas - myslím ze ukazovat jasně aktuálnost dat je důležité ! Díky za
issue i zpracování !

O.

ne 14. 11. 2021 v 15:30 odesílatel katkolouchova ***@***.***>
napsal:

**Comment by katkolouchova** [comment]
@mukrop Martine, jak to vypadá s přidáním tohoto disclaimeru? Myslím, že by stačilo, kdybys tam dal tu větu výše: _Informace jsou platné k říjnu 2021. Od té doby se k uhlíkové neutralitě přihlásily další státy (např. Indie)._

Díky moc :)

**Comment by mukrop** [comment]
Ja som cakal na finalne rozhodnutie, ci chcete len banner a s akym textom (tym padom sme sa asi nepochopili, ze tento text uz bol navrh finalneho). Nachystam pull request a dam ti na review (asi zajtra).

**Comment by katkolouchova** [comment]
Nepochopili, ale to nevadí :) Díky moc!
