### ISSUE TITLE
Upravit formulaci v grafice Uhlíkový rozpočet ČR

### ISSUE THREAD

**Issue by kikinna** [faktaoklimatu/web-cz#956]
https://faktaoklimatu.cz/infografiky/uhlikovy-rozpocet-cr

V grafice první bod "... bylo v roce 2020 možné celosvětově vypustit 650 Gt CO2" je zavádějící/těžký na správnou interpretaci. Nabíhá na interpretaci, že tolik emisí (650 Gt) jsme mohli vypustit jen v roce 2020. Text by měl jednoznačně komunikovat, že to je uhlíkový rozpočet, tedy množství emisí, které můžeme vypustit v budoucnu, po roce (od roku?) 2020. Nikoliv jen v daný rok.

**Comment by Jirka-tisnov** [comment]
Rozumím. Navrhuju: "...může svět od roku 2020 vypustit celkem 650 Gt CO2 (=globální uhlíkový rozpočet)". 
Přijde ti, že se to tím řeší?

**Comment by kikinna** [comment]
Poprosím, aktualizujete grafiku na webu? Je tam jen textová úprava v prvním bodě.

[cs-uhlikovy-rozpocet-cr.pdf](https://github.com/faktaoklimatu/web-cz/files/7539530/cs-uhlikovy-rozpocet-cr.pdf)
