### ISSUE TITLE
Oprava odkazu u grafiky "Emise skleníkových plynů v ČR podle sektorů detailně ČR"

### ISSUE THREAD

**Issue by vitekmilan** [faktaoklimatu/web-cz#974]
U infografika [faktaoklimatu.cz%2Finfografiky%2Femise-cr-detail](https://faktaoklimatu.cz/infografiky/emise-cr-detail)
prosím o opravu odkazu z emisních povolenek (https://ec.europa.eu/clima/sites/clima/files/ets/registry/docs/verified_emissions_2018_en.xlsx) odkazuje na zřejmě již neexistující stránku takže tam to ověřit nemohu.

**Comment by mukrop** [comment]
Aktualizovat to zvladnem, ale potrebujem ten novy link. Netusite nahodou @mgrabovsky alebo @jankrcal?

**Comment by mgrabovsky** [comment]
Odkazy na tabulky až do roku 2020 jsou na [téhle stránce](https://ec.europa.eu/clima/eu-action/eu-emissions-trading-system-eu-ets/union-registry_en) (sekce _Reports_).

**Comment by jankrcal** [comment]
Diky, Mateji!

**Comment by vitekmilan** [comment]
Díky moc!
