### ISSUE TITLE
Úprava textu o ceně povolenek

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-cz#976]
V infografike [Uhelný phase-out ve státech EU](https://faktaoklimatu.cz/infografiky/uhelny-phaseout-eu#:~:text=D%C3%ADky%20zm%C4%9Bn%C3%A1m%20v%C2%A0syst%C3%A9mu%20cena%20tuny,asi%2020%20EUR%20za%20tunu%20CO2) je v texte uvedena priama cena povoleniek vez uvedeneho datumu (len systemom "teraz" a "v minulom roku"). Je tam sice odkaz na aktualnu cenu, ten ale cene v texte vobec nezodpoveda.

Mohol by som niekoho poprosit o navrhnutie novej formulacie textu, ktora bude odolna plynutiu casu? (Bud sa vyhnut priamej cene alebo doplnit casovu znamku, kedy tato cena platila.) Ak navrhnete formulaciu sem do vlakna, ja to aktualizujem (je to pre mna aktualne blocker na zverejnenie slovenskej verzie infografiky).

Mozem poprosit napriklad @protivinsky?

PS: Uvedomujem si, ze v infografike je asi viacero neaktualnych informacii. Koncepcne tento problem budeme riesit upozorneniami na vybranych miestach, vid #958.

**Comment by protivinsky** [comment]
Ok, vytvorim opravu pro CZ uhelny phase-out. Otazkou ale je, jakym zpusobem budeme takove opravy delat - napiseme dolu nejaky disclaimer, kdy probehla oprava a ceho se tykala?

**Comment by mukrop** [comment]
Opravil @protivinsky.
