### ISSUE TITLE
Kontrola a případná oprava jména Fouriere -> Fourier

### ISSUE THREAD

**Issue by vitekmilan** [faktaoklimatu/web-cz#978]
Dotali jsme zpětnou vazbu z Twitteru - "Jen ten první teoretik skleníkového efektu se jmenoval Fourier, ne Fouriere jak máte v odkazu."

Jde to totu grafiku, prosím o kontrolu a případnou opravu. 
https://faktaoklimatu.cz/infografiky/historie-sklenikoveho-efektu

**Comment by katkolouchova** [comment]
Díky, mrknu na to.
