### ISSUE TITLE
Updatovat grafiku uhelný phase-out

### ISSUE THREAD

**Issue by katkolouchova** [faktaoklimatu/web-cz#995]
Už můžeme grafiku aktualizovat o:
- Česko (2033)
- Slovinsko (2033) – https://www.euractiv.com/section/politics/short_news/slovenia-to-exit-coal-by-2033/
- a pak i Rumunsko (2032), Bulharsko (2038 nebo 2040) a Chorvatsko (2033) – https://beyond-coal.eu/coal-exit-tracker/

- zároveň Portugalsko už zavřelo svoji posl. uhelnou elektrárnu v listopadu 2021, takže lze v grafice změnit na stav phase-out dončen

Co myslíš, @jankrcal?

**Comment by mgrabovsky** [comment]
A mozna i Nemecko na 2030 (podle [koalicni smlouvy](https://www.greenpeace.org/czech/tiskova-zprava/15298/nemecko-zkracuje-konec-uhli-na-rok-2030/)).

**Comment by jankrcal** [comment]
Jo, souhlas. Ke každé aktualizované zemi by to chtělo pěkný zdrojový link.
Katko, pustíš se do toho nebo ještě sbíráme změny?

**Comment by katkolouchova** [comment]
Pustím se do toho.

**Comment by jankrcal** [comment]
2049 mi přijde spíš výsměch, tak bych to tam nedával.
Taky to trochu rozhodí grafiku, asi by se to muselo trochu zmáčknout.

Tedy spíš bych to nechal, že seriózní termín ještě nemají.
Ale klidně se nechám přesvědčit.

**Comment by ondraspribyla** [comment]
... a otázka je, k čemu je donutí trh. Spíš dejme, že seriózní termín
nemají, a v textu pod grafikou dopišme že navrhují 2049?

**Comment by katkolouchova** [comment]
Do grafiky se to vejde, vypadalo by to takto:
![image](https://user-images.githubusercontent.com/49321752/149789329-99cdde5f-fc7f-44cc-8057-09a36205ce9e.png)

Otázkou je, co je seriózní termín – když [vláda podepsala dohodu s odbory](https://www.dw.com/en/poland-clinches-historic-deal-to-phase-out-coal-by-2049/a-57367983), že do r. 2049 těžbu ukončí. Uznávám, že je to výsměch. Navíc to zatím ani neschválila Komise. Ale jak to jinak do grafiky zanést? Protože pak mi nepřijde, že termín není a nehledá se úplně neodpovídá a probíhá hledání termínu taky ne.

**Comment by ondraspribyla** [comment]
...asi "probíhá hledání termínu" (každopádně to zůstane červený)
