### ISSUE TITLE
Oprava TWh -> kWh

### ISSUE THREAD

**Issue by vitekmilan** [faktaoklimatu/web-cz#999]
V grafice https://faktaoklimatu.cz/infografiky/elektrina-na-osobu-svet máme v popisu české spotřeby - první odstavec pod "Jak číst tento graf" chybu v jednotkách. Ačkoli je celá grafika i komentáře v kWh, tak píšeme, že česko má TWh, což nedává smysl.

**Comment by katkolouchova** [comment]
Díky za upozornění, upravuju :)

**Comment by vitekmilan** [comment]
Díky moc - jdu si najít, jak se do Gitu přidávají tagy :-)
